### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by vitalyermolovich** [ilteoood/flutter_i18n#1]
How to set default translations, for example, a  phone has Korean lang on setting, but translations are only English and Russian in app?

**Comment by ilteoood** [comment]
There is no fallback available, for now.
The fallback is the key that you use for the translation.

**Comment by ilteoood** [comment]
Hi @vitalyermolovich,
I've implemented the fallback logic with the version 0.1.0.
You can specify, as second parameter of FlutterI18nDelegate, the name of the file to use as fallback.
For more details, see: 76dfe3b62e0c9d3fdfb2f46cb46b01ab3e0938e6

Matteo
