### ISSUE TITLE
decodeStrategies with NetworkFileTranslationLoader

### ISSUE THREAD

**Issue by chicrock** [ilteoood/flutter_i18n#107]
I want to speed up the bootstrap process, using only one file format.
The decodeStrategies would help it.
But, the decodeStrategies prop is not in NetworkFileTranlationLoader.
Is there any way to use like decodeStrategies with NetworkFileTranlationLoader ?

**Comment by defint** [comment]
Hi @chicrock 
Added PR to solve your issue.
At this moment you can just use: `loader.decodeStrategies = [...];`

**Comment by ilteoood** [comment]
I've published version 0.16.1 to support it.
Please consider to upgrade to that version.

**Comment by chicrock** [comment]
@defint It's perfectly working! Thanks~ :)
