### ISSUE TITLE
Translated array support

### ISSUE THREAD

**Issue by jesusrp98** [ilteoood/flutter_i18n#11]
This new feature would bring the ability to return a translated array from the appropriate json file.
Here is an example:
```     
"people": [
    {
        "name": "Paul",
        "surname": "Freeman"
    },
    {
        "name": "Charles",
        "surname": "Beckham"
    },
    {
        "name": "Lucy",
        "surname": "Rooney"
    }
]
```
This would be an example of a call to the `array` method.
```
FlutterI18n.array(buildContext, "people").map((person) {
    print('My name is ${person['name']} and my surname ${person['surname']}.');
});
```
And the output would be:
```
My name is Paul and my surname Freeman.
My name is Charles and my surname Beckham.
My name is Lucy and my surname Rooney.
```
Thanks :)

**Comment by ilteoood** [comment]
Can you make an example with a real translation use case?
In that example you show data loaded from a json, without any logic about the language...that is not the aim of this library

**Comment by jesusrp98** [comment]
This is a real example of how this feature could be used. This array is made out of sports. Each sport has a name, and its tool's name.
```
"sports": [
    {
        "name": "Tennis",
        "tool": "Racket"
    },
    {
        "name": "Baseball",
        "tool": "Bat"
    },
    {
        "name": "Hockey",
        "tool": "Stick"
    },
    ...
]
```
This another example is another array, where all sports' name are single in the array. This could another great feature.
```
"sports": [
    "Tennis",
    "Baseball",
    "Hockey",
    ...
]
```
Thanks for considering it! :)

**Comment by ilteoood** [comment]
As I suspected, this is not a translation-related topic: you want to use this library to load different kind datamodel based on the locale.
This is not the aim of this library, sorry!
