### ISSUE TITLE
zh_CN and zh_TW both search for zh

### ISSUE THREAD

**Issue by ThinkSimple** [ilteoood/flutter_i18n#112]
Hey I need to implement both chinese simplified and chinese traditional into my App.  
When I set my phone to simplified chinese and print the locale i get 
 `I/flutter (13382): [flutter_i18n INFO]: New locale: de`
 `I/flutter (13382): [flutter_i18n INFO]: The system locale is zh_Hans_CN`
 `I/flutter (13382): [flutter_i18n INFO]: The current locale is zh_CN`
`I/flutter (13382): [flutter_i18n DEBUG]: Unable to load JSON file for zh`
`I/flutter (13382): [flutter_i18n DEBUG]: Unable to load YAML file for zh`
`I/flutter (13382): [flutter_i18n DEBUG]: Unable to load XML file for zh`

for traditional chinese it says:

`I/flutter (13382): [flutter_i18n INFO]: New locale: de`
`I/flutter (31892): [flutter_i18n INFO]: The system locale is zh_Hant_TW`
`I/flutter (31892): [flutter_i18n INFO]: The current locale is zh_TW`
`I/flutter (13382): [flutter_i18n DEBUG]: Unable to load JSON file for zh`
`I/flutter (13382): [flutter_i18n DEBUG]: Unable to load YAML file for zh`
`I/flutter (13382): [flutter_i18n DEBUG]: Unable to load XML file for zh`

Both chinese locales search for zh, but how can I seperate them?
Shouldn't it search for zh_TW if the current locale is zh_TW?
Thanks in advance and sorry if I missed something big.

**Comment by ilteoood** [comment]
Hi,
did you tried with useCountryCode parameter?

You can see how to use it in the README.md

**Comment by ThinkSimple** [comment]
Thank you!
