### ISSUE TITLE
Why is the language still not switched after long press the copy and paste pop-up box after the language switch? Why is this?

### ISSUE THREAD

**Issue by jiangqingbo** [ilteoood/flutter_i18n#113]
Why is the language still not switched after long press the copy and paste pop-up box after the language switch? Why is this? What can I do? thank you!

**Comment by jiangqingbo** [comment]
Hope to answer this question for me as soon as possible, thank you!

**Comment by jiangqingbo** [comment]
You must restart the app to be normal, but this is not the answer I want

**Comment by jiangqingbo** [comment]
Hope you can help me, thank you!

**Comment by jiangqingbo** [comment]
My code ：
Widget build(BuildContext context) {
    log("WelcomePage, languageCode=$languageCode");
    //将style设置到app
    SystemChrome.setSystemUIOverlayStyle(_style);
    return MaterialApp(
      theme: ThemeData(
        primaryColor: Color(AppColors.COLOR_PRIMARY),
        appBarTheme: AppBarTheme(brightness: Brightness.light), // light为黑色 dark为白色
      ),
      debugShowCheckedModeBanner: false,
      // 利用下面这种方式来对title属性进行国际化操作，避免直接设置title，那样无法国际化
      onGenerateTitle: (context) => FlutterI18n.translate(context, "app_name", translationParams: {"appName": Params.APP_NAME}),
      localizationsDelegates: [
        //应用程序的翻译回调
        FlutterI18nDelegate(
          translationLoader: FileTranslationLoader(
              useCountryCode: false,
              fallbackFile: languageCode,
              basePath: 'assets/i18n',
              forcedLocale: Locale(languageCode),
              decodeStrategies: [YamlDecodeStrategy()]),
        ),
        // 本地化的代理类
        GlobalCupertinoLocalizations.delegate,
        GlobalMaterialLocalizations.delegate, //Material组件的翻译回调
        GlobalWidgetsLocalizations.delegate, //普通Widget的翻译回调
      ],
      locale: Locale(languageCode,''),
      supportedLocales: [ // 添加区域
        const Locale('en', ''), // English
        const Locale('zh', ''), // Chinese
        // 可以继续添加我们想要支持的语言类型
      ],
      home: MainPage(),
    );
  }

**Comment by jiangqingbo** [comment]
After switching the language, I rerun this code. The language of the app has been switched, but the menu that appears after long press has not been switched.

**Comment by ilteoood** [comment]
Hi @jiangqingbo,
sorry but your problem isn't clear.
Can you expose it clearly **in a single message**, providing also some screenshots?
To switch language at runtime you should use the refresh method, but I can't understand what you're trying to do.

**Comment by jiangqingbo** [comment]
Hi @ilteoood 

In the input box, long press the box, the language has not changed, please see screenshots below, thank you!

<img width="542" alt="123" src="https://user-images.githubusercontent.com/1853417/86533427-c50d1f00-bf03-11ea-9f35-d0c386d49626.png">

**Comment by jiangqingbo** [comment]
<img width="542" alt="123" src="https://user-images.githubusercontent.com/1853417/86533505-44025780-bf04-11ea-8d4e-1f1a773cc54f.png">

**Comment by ilteoood** [comment]
Hi @jiangqingbo,
thank you so much. It is more clear now.
What do you use to create that pop-up? Can you create a sample app with which I can reproduce this behavior?

Thank you so much,
Matteo

**Comment by jiangqingbo** [comment]
@ilteoood  
Long press in the input textfield and it will appear

**Comment by ilteoood** [comment]
Ok. Now is really clear.
That pop-up is provided by the system, so it depends on the system language.
It has nothing to do with Flutter or this library. Is the same behaviour that you have on the left of the clock: the language for the objects provided by the system, is the system language.

**Comment by jiangqingbo** [comment]
@ilteoood 
However, the application restarts and it's OK.

**Comment by jiangqingbo** [comment]
Language switching doesn't work in apps
