### ISSUE TITLE
Can't update translations for same language

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [ilteoood/flutter_i18n#116]
In my situation i'm not aiming to switch between languages. But i'm aiming to update the translations in the same language.
let's consider that we have only one lang ```Local('en')``` and while app is running the server push notifications to me with new translations, I handle the notification and replace the old translations with the new one in the  app local storage ```await getApplicationDocumentsDirectory();```, Then i reload and refresh every thing
```dart
await flutterI18nDelegate.load(Locale('en'));
await FlutterI18n.refresh(context, Locale('en'));
setState(() {});
```
But unfortunately no thing changed. And i had to restart the app But this is not that i want. I want to make while app is running.
```dart
  final appDocDir = await getApplicationDocumentsDirectory();
  final langsPath = '${appDocDir.path}/langs';

  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
    translationLoader: FileTranslationLoader(
      useCountryCode: false,
      basePath: langsPath,
      forcedLocale: Locale('en'),
      decodeStrategies: [JsonDecodeStrategy()],
    ),
  );
  await flutterI18nDelegate.load(Locale('en'));

  runApp(I18nApp(flutterI18nDelegate));
```
Please help.

**Comment by ilteoood** [comment]
This seems strange to me.
I can tell you that you shouldn't call the load method of the delegate: the refresh one is sufficient.
Are you sure that the data inside local storage is updated, before the invocation of the refresh method?
Every time that you call the refresh method, the translation map is rebuilt from scratch.
Did you tried to debug this line (https://github.com/ilteoood/flutter_i18n/blob/e412ab22ee6a495fac095c5c5276c05e2b0cee93/lib/loaders/decoders/base_decode_strategy.dart#L15) when you invoke call refresh, in order to see the content?

**Comment by AlaaEldeenYsr** [comment]
> when you invoke call refresh, in order to see the content loaded?

Just after updating the translations json file in the local storage.

And there is two evidence on the issue, First one is that when i restart the app the package reads the new translations well.
The second evidence on the issue and this is more clear, That when i replace the translations json file in the local storage with a different name it works, That means that as long as the file name not changed so the package will read the file with the old content and the new translations in the file won't be updated in the ui, but if the file name got changed during replacing the new translations so the package will read the new translations in the file and the ui is updated.

Here is the code to fetch the updated translations and replace it with the old with the same file name ( Not working - Ui not updated )
```
final appDocDir = await getApplicationDocumentsDirectory();
final langsPath = '${appDocDir.path}/langs';
final filePath = '$langsPath/en.json';
final file = File(filePath);

print(jsonDecode(file.readAsStringSync())); // {save: Test Fla}
file.writeAsStringSync((await get('http://4d5a49498fe3.ngrok.io')).body);
print(jsonDecode(file.readAsStringSync())); // {save: Different Text Here}
await FlutterI18n.refresh(context, Locale('en'));
setState(() {});
```


And here is the same code but with a different file name ( Works - Ui updated)
```
final appDocDir = await getApplicationDocumentsDirectory();
final langsPath = '${appDocDir.path}/langs';
final filePath = '$langsPath/en2.json'; <<<<<<<<<<<<- different name
final file = File(filePath);

print(jsonDecode(file.readAsStringSync()));
file.writeAsStringSync((await get('http://4d5a49498fe3.ngrok.io')).body);
print(jsonDecode(file.readAsStringSync()));
await FlutterI18n.refresh(context, Locale('en2')); <<<<<<<<<<<- different name
setState(() {});
```
I hope this is clear for you @ilteoood

**Comment by AlaaEldeenYsr** [comment]
Here is the code
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final appDocDir = await getApplicationDocumentsDirectory();
  final langsPath = '${appDocDir.path}/langs';
  final langsDir = Directory(langsPath);
  if (!langsDir.existsSync()) langsDir.createSync();
  final filePath = '$langsPath/en.json';
  final file = File(filePath);
  if (!file.existsSync()) {
    file.writeAsStringSync((await get('http://4d5a49498fe3.ngrok.io')).body);
  } else {
    print('Already exists');
  }

  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
    translationLoader: FileTranslationLoader(
      useCountryCode: false,
      basePath: langsPath,
      forcedLocale: Locale('en'),
      decodeStrategies: [JsonDecodeStrategy()],
    ),
  );
  await flutterI18nDelegate.load(Locale('en'));

  runApp(Test(flutterI18nDelegate));
}

class Test extends StatefulWidget {
  Test(this.flutterI18nDelegate);
  final FlutterI18nDelegate flutterI18nDelegate;

  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        widget.flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      home: Builder(
        builder: (context) => Scaffold(
          appBar: AppBar(title: Text('Test')),
          body: Column(children: <Widget>[
            FlatButton(
              onPressed: () async {
                final appDocDir = await getApplicationDocumentsDirectory();
                final langsPath = '${appDocDir.path}/langs';
                final filePath = '$langsPath/en.json';
                final file = File(filePath);

                print(jsonDecode(file.readAsStringSync()));
                file.writeAsStringSync((await get('http://4d5a49498fe3.ngrok.io')).body);
                print(jsonDecode(file.readAsStringSync()));
                await FlutterI18n.refresh(context, Locale('en'));
                setState(() {});
              },
              color: Colors.purple,
              padding: const EdgeInsets.all(20),
              child: Text('update'),
            ),
            Container(
              color: Colors.blue,
              padding: const EdgeInsets.all(40),
              child: I18nText('save'),
            ),
          ]),
        ),
      ),
    );
  }
}
```

**Comment by ilteoood** [comment]
Ok, with this kind of explaination is more clear.
I've found the problem: loadString, as default, has a bool cache: true parameter.
I've removed it; please consider to upgrade to version 0.16.3, that I'm publishing right now.

**Comment by AlaaEldeenYsr** [comment]
Awesome 😍😍, Thank you pro @ilteoood  See you next issue.
