### ISSUE TITLE
rtl not working with rtl languages

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [ilteoood/flutter_i18n#117]

**Comment by ilteoood** [comment]
Are you using the supportedLocales parameter of MaterialApp?

**Comment by AlaaEldeenYsr** [comment]
> Are you using the supportedLocales parameter of MaterialApp?

@ilteoood  Yes i tried it 
```dart
MaterialApp(
      localizationsDelegates: [
        widget.flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: [
        Locale('en'),
        Locale('ar'),
      ],
    )
```
And no thing happened. It's not about the ```supportedLocales``` but it's about the ```local``` parameter of the The Material App
The Material App decides the directionality of the app based on the ```Local('ar')``` value you pass to the ```local``` parameter
```dart
    MaterialApp(
      localizationsDelegates: [
        widget.flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      locale: FlutterI18n.currentLocale(context),  //<<<<<<<<< Here
    )
```
Also the previous example won't work and will fire an exception about the wrong context you pass here ```locale: FlutterI18n.currentLocale(context)```, Because that context is above the Material App and not of its children so it can't see it. So i tried the next example and it worked well
```dart
    MaterialApp(
      localizationsDelegates: [
        widget.flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      builder: (context, home) => Localizations( // child context
        delegates: [
          widget.flutterI18nDelegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        locale: FlutterI18n.currentLocale(context), // child context
      ),
      home: Home(),
    )
```

**Comment by AlaaEldeenYsr** [comment]
I think we can do this instead of the extra nested ```Localizations``` Widget in  the previous comment https://github.com/ilteoood/flutter_i18n/issues/117#issuecomment-658260061
```dart
    MaterialApp(
      localizationsDelegates: [
        widget.flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      locale: widget.flutterI18nDelegate.currentLocale,
    )
```
But unfortunately it's not working, The app still on a fixed directionality even if i switched to an rtl language ```FlutterI18n.refresh(context, Locale('ar'))```

**Comment by ilteoood** [comment]
Please upgrade to 0.17.0 and use the new rootAppBuilder.

**Comment by Leeeeerich** [comment]
I have some problems: 
i use:

```
 MaterialApp(
        localizationsDelegates: [
          widget._flutterI18nDelegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        builder: FlutterI18n.rootAppBuilder(),
        locale: widget._flutterI18nDelegate.currentLocale,
      ),
    );
```

I see in logs:

`I/flutter (14169): [flutter_i18n INFO]: New locale: null
I/flutter (14169): [flutter_i18n INFO]: The system locale is ar_EG
I/flutter (14169): [flutter_i18n INFO]: The current locale is ar_EG
I/flutter (14169): [flutter_i18n INFO]: JSON file loaded for ar
I/flutter (14169): [flutter_i18n DEBUG]: Unable to load YAML file for ar
I/flutter (14169): [flutter_i18n DEBUG]: Unable to load XML file for ar
I/flutter (14169): [flutter_i18n INFO]: JSON file loaded for en
I/flutter (14169): [flutter_i18n DEBUG]: Unable to load YAML file for en
I/flutter (14169): [flutter_i18n DEBUG]: Unable to load XML file for en
I/flutter (14169): [flutter_i18n INFO]: New locale: en_US
I/flutter (14169): [flutter_i18n INFO]: The current locale is en_US
I/flutter (14169): [flutter_i18n INFO]: JSON file loaded for en
I/flutter (14169): [flutter_i18n DEBUG]: Unable to load YAML file for en
I/flutter (14169): [flutter_i18n DEBUG]: Unable to load XML file for en
I/flutter (14169): [flutter_i18n INFO]: JSON file loaded for en
I/flutter (14169): [flutter_i18n DEBUG]: Unable to load YAML file for en
I/flutter (14169): [flutter_i18n DEBUG]: Unable to load XML file for en
I/flutter (14169): [flutter_i18n INFO]: New locale: en_US`

Why it reseted to en? In device using arabic (Egypt)

**Comment by Leeeeerich** [comment]
Ha-Ha, I found problems: I didn't added `supportedLocales: [Locale("en"), Locale("ar")],`. But if I use a plugin for localizations, I waiting for what it's without me will include. Okay, I think need to add to the guide about: need including supportedLocales: [Locale("en"), Locale("yours locales"), ...],
