### ISSUE TITLE
Translations file get loaded after flutter builds its widget tree which leads to rendering translations keys not its values

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [ilteoood/flutter_i18n#119]
This issue only happens when the basePath of the translations file is from the local storage not the assets ```getApplicationDocumentsDirectory()```

Alright, What's happens that when i open the app i see the keys of the translations not the value, And this is because that the operation of loading the json file from the local storage ```getApplicationDocumentsDirectory()``` is an async operation which takes about a second, And flutter doesn't wait for that, Flutter builds its widgets tree synchronously, And that leads to rendering the keys of the translations not its values, And once i make a hot reload then i can see the translations values well, Because the async operation of loading the json file got finished after flutter builded its widgets tree.

So i think that there must be a way for handling that loading operation. Either by showing loading widget and  for example or provide a way to ```await``` the loading operation before the widgets tree be builded.

Here is the code, once you open the app you will see the ```contactUsSubTitle``` key is rendered in the ui, Try to make a hot reload or a hot restart and the value is rendered. If you want to reproduce again you should close the app and run it from scratch don't consider hot restart as you won't see any problem.
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // download translations and store on the local storage
  final appDocDir = await getApplicationDocumentsDirectory();
  final langsPath = '${appDocDir.path}/langs';
  final filePath = '$langsPath/en.json';
  final file = File(filePath);
  final trResponce = await get('http://appstage.tielabs.com//wp-json/wl/v1/language?language=en');
  final langsDir = Directory(langsPath);
  await langsDir.create();
  await file.create();
  await file.writeAsString(trResponce.body);
  print(await file.readAsString()); // <<<<<<<<< translations

  final flutterI18nDelegate = FlutterI18nDelegate(
    translationLoader: FileTranslationLoader(
      basePath: langsPath,
      decodeStrategies: [JsonDecodeStrategy()],
    ),
  );
  await flutterI18nDelegate.load(Locale('en'));

  runApp(Test(flutterI18nDelegate));
}

class Test extends StatefulWidget {
  Test(this.flutterI18nDelegate);
  final FlutterI18nDelegate flutterI18nDelegate;

  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        widget.flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      home: Builder(
        builder: (context) => Scaffold(
          appBar: AppBar(title: Text('Test')),
          body: Column(children: <Widget>[
            Container(
              color: Colors.blue,
              padding: const EdgeInsets.all(40),
              child: I18nText('contactUsSubTitle'),
            ),
          ]),
        ),
      ),
    );
  }
}
```
The problem here is that the release mode doesn't have a hot reload or a hot restart and every time i open the app i see the translations keys not values.

![ezgif com-video-to-gif (12)](https://user-images.githubusercontent.com/52201392/87568610-38fab480-c6c6-11ea-903b-68ada19621af.gif)

**Comment by ilteoood** [comment]
Just one question: why you manually download your translation file, when we have NetworkFileTranslationLoader?

**Comment by ourcoteam** [comment]
Yes, I'm facing that problem too, in my project I was using this method due to business needs which were needing to just connect to the server one time then download the data on storage and only retrieve it again when we make any changes on the online version, my solution was like you exactly, but unfortunately faced the same issue.

@ilteoood  I hope you can handle it with the same logic too.

**Comment by ilteoood** [comment]
Did you tried to change
void main() async {
to
Future main() async {

?

**Comment by ilteoood** [comment]
@defint I think we should add the cache to NetworkFileTranslationLoader, what do you think?

**Comment by AlaaEldeenYsr** [comment]
I'm not sure that this will give me the full flexibility i want, I need to download the translations and caching it manually, So if you just run the code sample in the first comment you will notice the issue very clear, we just need to ```await``` for the ```FileTranslationLoader``` till it completely loads the ```basePath```,  And you will notice these prints also in the console 
```
[flutter_i18n DEBUG]: Unable to load JSON file for en
[flutter_i18n DEBUG]: Error loading translation Bad state: No element
```
Then make a hot restart or a hot reload then the file loaded successfully, So why that happens ? It only works after a hot restart, The problem that the release mode doesn't have a hot restart.

**Comment by ourcoteam** [comment]
@ilteoood is there any update on this? you gave me hope.

**Comment by ilteoood** [comment]
As documented here:
https://github.com/ilteoood/flutter_i18n#filetranslationloader-configuration
"To use this library, you must create a folder in your project's root", so FileTranslationLoader should be used only when you have your translations inside the assets folder.
However, considering your needs, I've made a new TranslationLoader: LocalTranslationLoader. Please, consider to upgrade to version 0.18.0.

@AlaaEldeenYsr I've used your example, suitably modified, as example here: https://github.com/ilteoood/flutter_i18n/blob/master/example/lib/local_example.dart

@ourcoteam please, remember that this is an open source project. I work it on my spare time, don't ask for ETA.
