### ISSUE TITLE
How to localize a string variable

### ISSUE THREAD

**Issue by hupo376787** [ilteoood/flutter_i18n#12]
Hi, I'm new to flutter. I'm using this awesome project to localize my test app.
But I met a problem. How to localize a string variable?

```
class _HomePageState extends State<HomePage> {
  String hint= 'Tap 🌼 to start';
}
```

I can't use
`String hint= FlutterI18n.translate(context, 'hint');`

**Comment by ilteoood** [comment]
You can't.
The second parameter of the translate function is the string key for the translation. This key must be defined in the translation json.

Example:

it_IT.json:
{
"hint": "Premi qui per cominciare"
}

en_US.json:
{
"hint": "Tap here to start"
}

To localize this, you should then use: FlutterI18n.translatge(context, 'hint')
