### ISSUE TITLE
Is there a bug in "shouldReload"?

### ISSUE THREAD

**Issue by xiangxn** [ilteoood/flutter_i18n#122]
https://github.com/ilteoood/flutter_i18n/blob/master/lib/flutter_i18n_delegate.dart
```
@override
  bool shouldReload(final FlutterI18nDelegate old) {
    return this.currentLocale == null ||
        this.currentLocale == old.currentLocale;
  }
```
should be:
```
@override
  bool shouldReload(final FlutterI18nDelegate old) {
    return this.currentLocale == null ||
        this.currentLocale != old.currentLocale;
  }
```

**Comment by ilteoood** [comment]
Nope, with your suggestion if you update your translation file, it won't be hot reloaded.

**Comment by dukaric1991** [comment]
I also had a problem with shouldReload method, when i focused on any textfield it changed language to the fallback one... When i changed shouldReload method to return false, it works as expected now.
