### ISSUE TITLE
YAML file loaded but then it says can't load

### ISSUE THREAD

**Issue by ibrahimyu** [ilteoood/flutter_i18n#123]
Here's my code:

```
localizationsDelegates: [
      FlutterI18nDelegate(
        translationLoader: FileTranslationLoader(
          useCountryCode: false,
          basePath: 'assets/locales',
          // forcedLocale: Locale('zh'),
          decodeStrategies: [YamlDecodeStrategy()],
        ),
        missingTranslationHandler: (key, locale) {
          print("--- Missing Key: $key, languageCode: ${locale.languageCode}");
        },
      ),
      GlobalMaterialLocalizations.delegate,
      GlobalWidgetsLocalizations.delegate
    ],
```

And when running, it says:

```
I/flutter (14561): [flutter_i18n INFO]: New locale: en_US
I/flutter (14561): [flutter_i18n INFO]: The current locale is en_US
I/flutter (14561): [flutter_i18n INFO]: YAML file loaded for en
I/flutter (14561): [flutter_i18n DEBUG]: Unable to load YAML file for en
I/flutter (14561): [flutter_i18n DEBUG]: Error loading translation Bad state: No element
I/flutter (14561): [flutter_i18n INFO]: YAML file loaded for en
I/flutter (14561): [flutter_i18n DEBUG]: Unable to load YAML file for en
I/flutter (14561): [flutter_i18n DEBUG]: Error loading translation fallback Bad state: No element
I/flutter (14561): --- Missing Key: upcoming_activities, languageCode: en
I/flutter (14561): --- Missing Key: home, languageCode: en
```

It says YAML file loaded for en, so I know that the loader, basePath and file location is correct. However then it says unable to load YAML file for en, and massive missing key messages coming.

This works flawlessly before, just started to bug last night. Tried to flutter clean and rebuild, but still. If I remember correctly, I was running flutter pub run flutter_launcher_icons:main before this error happens. But it shouldn't affect anything, right?

Any ideas what else should I check? Any help is appreciated.

**Comment by ilteoood** [comment]
Hi,
Can you try to validate the yaml structure?
Copy-paste your file here: http://www.yamllint.com

**Comment by ibrahimyu** [comment]
Ah, it works now. It was a valid YAML, but then I replaced the file with generated text from yamllint. It seems I have to wrap values with spaces with double quote.
Thanks!
