### ISSUE TITLE
Unable to change the text on UI if I change the FlutterI18nDelegate

### ISSUE THREAD

**Issue by snj07** [ilteoood/flutter_i18n#125]
If I reload the `MaterialApp` using `BlocBuilder` builder then it does not reload the text on the screen. 
```dart
return MaterialApp(
        title: 'Flutter Demo',
        debugShowCheckedModeBanner: false,
        localizationsDelegates: [
          FlutterI18nDelegate(
              useCountryCode: true,
              fallbackFile: 'en_US',
              path: GlobalAppConstants.i18Path,
              forcedLocale: Locale(appLocaleModel.languageCode,
                  appLocaleModel.countryCode)),
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        home: MyHomePage(title: 'Flutter Demo Home Page'),
   );
```
I need to explicitly call `FlutterI18n.refresh()` on the page to refresh the text on the screen when I change the language.
```dart
await FlutterI18n.refresh(context, GlobalAppConfig.currentLocale);
```
Do I need to put `FlutterI18n.refresh()` on all the pages?

**Comment by ilteoood** [comment]
Sorry but isn't clear what you're trying to do.
Can you share your demo with me?

**Comment by snj07** [comment]
Please check [this](https://github.com/snj07/demo_i18n) demo. I am trying to change the language on click of a button and it's not getting reflected until I call `refresh()` though I created a new  `FlutterI18nDelegate` and assigned to `MaterialApp`. Please check `_handleChangeLocaleAppEvent()` in `app_bloc.dart`.

**Comment by ilteoood** [comment]
Man,
are you really open an issue with a version of the library published 6 months ago?
The latest version is 0.19.1, while you're using 0.8.3...

I suggest you to upgrade to the latest version, and for that I've prepared a git patch for you.
[demo_i18n.diff.zip](https://github.com/ilteoood/flutter_i18n/files/5092786/demo_i18n.diff.zip)

Good luck,
Matteo
