### ISSUE TITLE
Screen went black

### ISSUE THREAD

**Issue by tzh-goon** [ilteoood/flutter_i18n#126]
When using Network Loading，Screen went black at Begining, 
How to resolve it?

**Comment by defint** [comment]
Probably your translations are loading for a long time. 
Under the hood, we use `NetworkAssetBundle` which just load assets from the network without any flexibility.

@ilteoood 
Do we have lazy-loading functionality? If not - I can try to thought about this.

**Comment by ilteoood** [comment]
Hi @defint, the isn't any lazy-loading functionality. I would like to introduce a sort of cache...
@tzh-goon did you tried the async approach implemented in the example app?

**Comment by tzh-goon** [comment]
@ilteoood 
`
class _NetworkAssetBundle extends AssetBundle {
  @override
  Future<ByteData> load(String key) => null;

  @override
  Future<T> loadStructuredData<T>(String key, parser) {
    return Api.getSAKILanguageData(key).then(jsonDecode).then((e) => e as T);
  }
}
`

**Comment by ilteoood** [comment]
Sorry, I don't understand. What's this?

**Comment by ilteoood** [comment]
Ping

**Comment by ilteoood** [comment]
Information not provided. Close due to inactivity.
