### ISSUE TITLE
Health of translations

### ISSUE THREAD

**Issue by defint** [ilteoood/flutter_i18n#127]
Hi @ilteoood 

In my project, I want to have the next information about translation files:
- percentage of completed translations; (for example "en: 100%, uk: 60%, ru: 85%")
- all non-translated keys;

With this info, we can the check health of translations during CI/CD process. The simplest way to achieve this - create a special method in the `TranslationLoader`. 

If you do not mind - I'll create PR.

**Comment by ilteoood** [comment]
Hi @defint,
that's a curious point of view: usually I would do this with external tools.
Please, show me your proposal.

**Comment by defint** [comment]
Unfortunately, it is not to easy as I think.
We need to use Flutter classes which cannot be used inside CLI runs.
Also, we cannot use it during Flutter run, because we need to use the file system to save the result.
At this time I postpone this issue but will turn back after getting some workaround.
