### ISSUE TITLE
Why do you execute _loadCurrentTranslations first and then _loadFallback

### ISSUE THREAD

**Issue by jlcool** [ilteoood/flutter_i18n#13]
Why do you execute _loadCurrentTranslations first and then _loadFallback

**Comment by ilteoood** [comment]
The _loadFallback is called only if there isn't a translation file for the current system language. Isn't called always.

**Comment by jlcool** [comment]
There is no way to use the language set by the user at the next boot. He will always use only the system language.

**Comment by ilteoood** [comment]
You can configure the delegate or use the refresh method

**Comment by jlcool** [comment]
Because first execute _loadCurrentTranslations, and then I set the JSON file to the same system language, he will always use this file. I see you only find the language I set when there is no system language file (throwing an exception). I think the _loadCurrentTranslations method is useless.
