### ISSUE TITLE
translationParams not working

### ISSUE THREAD

**Issue by aarajput** [ilteoood/flutter_i18n#130]
This is my en.json file
`{
    "version": "Version $versionName"
}`

but when i try to translate it using
`FlutterI18n.translate(
      context,
      'version',
      translationParams: {'versionName': '5.1.2'});`

It prints **_Version $versionName_** instead of **_Version 5.1.2_**

**Comment by defint** [comment]
Hi @aarajput 

Please check the example of JSON file: https://github.com/ilteoood/flutter_i18n/blob/baba5e22fe858e679dcd5d522ababb8b665b6736/example/assets/i18n/it.json

**Comment by aarajput** [comment]
@defint ! I replaced 
`{ "version": "Version $versionName" }`
with
`{ "version": "Version {versionName}" }`

and it worked.

Thanks for your help.
