### ISSUE TITLE
Translations not working on iOS 14 

### ISSUE THREAD

**Issue by freddy-nawfal** [ilteoood/flutter_i18n#132]
As mentioned in the title, I noticed that the translations do not work since I upgraded to iOS 14. Nothing else has changed code-wise. The only translation that actually works is the base one (fallbackFile: "en").

Here is my flutter doctor for reference: 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.49.3)
[✓] Connected device (1 available)
```

And here is the version of the plugin that I'm using: 
`flutter_i18n: ^0.19.4`

**Comment by ilteoood** [comment]
Hi,
did you tried with: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-updating-the-ios-app-bundle

An example of the content can me:

<key>CFBundleLocalizations</key>
<array>
	<string>en</string>
	<string>nb</string>
</array>

**Comment by ilteoood** [comment]
Hi,
did you tried with: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-updating-the-ios-app-bundle

An example of the content can be:

```xml
<key>CFBundleLocalizations</key>
<array>
	<string>en</string>
	<string>nb</string>
</array>
```

**Comment by freddy-nawfal** [comment]
Thanks, it works but I also had to add the "supportedLocales" parameter in the MaterialApp with the list of all supported languages.
