### ISSUE TITLE
Changing KEY_SEPARATOR

### ISSUE THREAD

**Issue by kmaxion** [ilteoood/flutter_i18n#135]
Hey, this is more of a suggestion.

For my use case it would be really useful to be able to change the separator used to parse the key passed to translate() because my i18n files have keys that contain periods.

Would it be possible to add this feature?

**Comment by ilteoood** [comment]
Hi @kmaxion,
sure! I'll try to add it ASAP.

**Comment by ilteoood** [comment]
Support introduced with commit:
https://github.com/ilteoood/flutter_i18n/pull/136/commits/729a036b0698fe509486f5a89ce355b3864275bb

Hope it'll be available in 0.20.0
