### ISSUE TITLE
DevTools - Select Widget Mode

### ISSUE THREAD

**Issue by SeFeX** [ilteoood/flutter_i18n#137]
When I activate widget selection mode in Dart DevTools it throws an exception of "Bad State: Stream has already been listened to."

> The following StateError was thrown building Builder(dependencies:
> [_LocalizationsScope-[GlobalKey#97345]]):
> Bad state: Stream has already been listened to.
> The relevant error-causing widget was:
> MaterialApp                        lib\main.dart:37
> When the exception was thrown, this was the stack:

![image](https://user-images.githubusercontent.com/8743081/96358820-22069c80-10d1-11eb-858d-a978420c7f85.png)

![image](https://user-images.githubusercontent.com/8743081/96358844-43678880-10d1-11eb-8647-3a50d073daea.png)

- Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.508], locale en-GB)
- Dart version 2.9.2
- Android SDK version 30.0.2

![image](https://user-images.githubusercontent.com/8743081/96358897-ba9d1c80-10d1-11eb-8d9a-3de70611affa.png)

**I don't know if this goes here or in the Dart DevTools issues, the fact is that without the library `flutter_i18n` the select widget mode works fine**

**Comment by ilteoood** [comment]
That's really strange. Are you using one of the stream introduced in 0.20.0?

**Comment by SeFeX** [comment]
No, I only use the translation function, this is an example, all app translations are the same with different key
`FlutterI18n.translate (context," onboarding.skip ")`

**Comment by ilteoood** [comment]
Can you reproduce it with the example app provided?
I'm trying with it but without any luck:
![image](https://user-images.githubusercontent.com/6383527/96501236-640a1c80-1250-11eb-86d6-e72adb16bd9b.png)

**Comment by SeFeX** [comment]
Steps reproduced with Android Studio, I created a new flutter project, I imported the `flutter_i18n` library, the translation works correctly, but when activating Flutter Inspector, which has been the same Flutter DevTools, and clicking on the Select Widget Mode option, it causes a exception in the MaterialApp widget:

![image](https://user-images.githubusercontent.com/8743081/96521361-b76f7100-1236-11eb-9e12-50f632fc5a8e.png)

Showing how Select Widget Mode works without the library:
![image](https://user-images.githubusercontent.com/8743081/96521597-39f83080-1237-11eb-89a8-9fac185577b2.png)

**Comment by ilteoood** [comment]
Found it!
Thank you so much, it'll be fixed with 0.20.1
