### ISSUE TITLE
Is it possible to call FlutterI18n.translate outside widgets where there is no buildContext object

### ISSUE THREAD

**Issue by DiaaEddin** [ilteoood/flutter_i18n#138]

**Comment by defint** [comment]
Hi @DiaaEddin 
You cannot use translation outside context.
Please describe your use case and I will help you with a solution.

**Comment by ilteoood** [comment]
Close for inactivity.

**Comment by otto-dev** [comment]
I was looking how to do this.

My use-case: I have a bunch of objects with translation `keys` (error messages), and I want to unit-test that all of them exist in the default language.

**Comment by ilteoood** [comment]
Hi @otto-dev,
there is the following PR to do this:
https://github.com/ilteoood/flutter_i18n/pull/188

Unfortunately, tests are missing.
