### ISSUE TITLE
How to localize app name shown in desktop/menu list?

### ISSUE THREAD

**Issue by hupo376787** [ilteoood/flutter_i18n#14]
Hi, how to localize app name shown in desktop/menu list?
For example, "Play Store", in Chinese is "Play 商店".
Thanks.

![default](https://user-images.githubusercontent.com/14960168/52829326-45f92a00-3107-11e9-8e64-a322dcc9c5dd.jpg)

**Comment by ilteoood** [comment]
Hi @hupo376787,
You can't do this with flutter_i18n. To achieve this, you should configure the android:label property on the manifest to use the native Android translation, with the .xml files
