### ISSUE TITLE
Question: Is it possible to use both FileTranslationLoader and NetworkFileTranslationLoader

### ISSUE THREAD

**Issue by Wouter12** [ilteoood/flutter_i18n#140]
Hi,

I'm working on an app which both has local translations in a json and fetches translations from our backend service.
It seems to me that only the translations from the backend service or the file are available in the app, depending on which TranslationLoader I create last.

**Comment by defint** [comment]
Hi @Wouter12 

You can use only one of the predefined translation loader. But you can easily create your own custom translation loader with the necessary logic to split them.

**Comment by ilteoood** [comment]
What you can do is download the translation from your backend service and keep it in device memory.
To do this, you can use the LocalTranslationLoader; please check this example:
https://github.com/ilteoood/flutter_i18n/blob/master/example/lib/local_example.dart
