### ISSUE TITLE
can translate support a list?

### ISSUE THREAD

**Issue by javyliu** [ilteoood/flutter_i18n#142]
translate only return a String ,if i defined a array in yaml, can it return a list?

**Comment by defint** [comment]
Hi @javyliu 

You have to have only key-value structure of your translation files.

**Comment by ilteoood** [comment]
Can u describe us your use case? A list in a translation file is quite unusual

**Comment by ilteoood** [comment]
Close for inactivity.

**Comment by MichaelOdumosu57** [comment]
Greetngs I have a use case for this. our angular with ngx translate supports list. its is for covnience now I have a whole production application. I rather not modify the json files because the angular package supports lists and the flutter package does not is there anyway around this?
