### ISSUE TITLE
intl 0.17.0-nullsafety.2 is needed as new dependency

### ISSUE THREAD

**Issue by moda20** [ilteoood/flutter_i18n#146]
i am trying to `pub get` and I am getting a versioning error for this repo on version 0.20.1  since it still used `intl 0.16.0` instead of the new `intl 0.17.0-nullsafety.2` since the null safety is a thing now. 
please update.

here is the error : 
```
pub get failed (1; So, because App depends on flutter_i18n ^0.20.1 which
depends on intl ^0.16.0, version solving failed.)
```

**Comment by ilteoood** [comment]
I'll not update untile 0.17 will be officially release: now is in pre-release.
I suggest you to override the dependency, including the follow in your pubsec:

dependency_overrides:
   intl: ^0.17.0-nullsafety.2

**Comment by ilteoood** [comment]
I've made a pre release of the library in order to support this: 0.21.0-intl.nullsafety
