### ISSUE TITLE
Incompatible version of 'intl' after did "Flutter Upgrade"

### ISSUE THREAD

**Issue by JmyW** [ilteoood/flutter_i18n#147]
Today I run flutter upgrade in Android Studio. Afterwards, the "Flutter Pub Get" keeps an error message as following: 
It looks like you are using intl 0.16.0 that's incompatible with latest 0.17.0. Should you update it?

============================================================================
Because flutter_i18n >=0.11.1 depends on intl ^0.16.0 and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, flutter_i18n >=0.11.1 is incompatible with flutter_localizations from sdk.
So, because kindergarten depends on flutter_i18n ^0.20.1 which depends on flutter_localizations any from sdk, version solving failed.
pub get failed (1; So, because kindergarten depends on flutter_i18n ^0.20.1 which depends on flutter_localizations any from sdk, version solving failed.)

**Comment by ilteoood** [comment]
Duplicate of https://github.com/ilteoood/flutter_i18n/issues/146

**Comment by ilteoood** [comment]
I've made a pre release of the library in order to support this: 0.21.0-intl.nullsafety
