### ISSUE TITLE
NetworkFileTranslationLoader : Unable to load JSON file for en => Bad state: No element

### ISSUE THREAD

**Issue by ALBRECHTMike** [ilteoood/flutter_i18n#148]
Hello,
Im trying since few days to pass from Local Json translators files loaders
to Network Files Loader method.

`NetworkFileTranslationLoader(
      baseUri: uri,
      useCountryCode: false,
      fallbackFile: 'fr',
      ),`

with : 
`final Uri uri = Uri.http("www.baylse-services.com", "i18nget" )`

and i receive the Error : **Unable to load JSON file for en => Bad state: No element**

The APi works great like : [http://www.baylse-services.com/i18nget/en.json](http://www.baylse-services.com/i18nget/en.json)

Please, could you tell me where im wrong ?
Regards, Mike

**Comment by ilteoood** [comment]
I think that your URI must be declared as:
Uri.http("www.baylse-services.com", "i18nget/")

**Comment by ALBRECHTMike** [comment]
OK it works. many thanks

**Comment by alevittoria** [comment]
Ok but please, update the README.
Thanks a lot!

**Comment by ilteoood** [comment]
@alevittoria you can always send a PR :)
