### ISSUE TITLE
Use singleton instead of static

### ISSUE THREAD

**Issue by moseskarunia** [ilteoood/flutter_i18n#153]
Hello. first of all, great package. I just wanna ask. Is there any plan to update the function for translation to use singleton instead of static? The reason for this is to make it easier to stub in widget tests.

Proposed usage:

```dart
class MyWidget extends StatelessWidget {
  final FlutterI18n flutterI18n;
  
  MyWidget({@required this.flutterI18n});

  @override
  Widget build(BuildContext context) {
    return Text(
      flutterI18n.translate(context, 'label.myWidget.title');
    );
  }
}
```

```dart
/// Test file

class MockI18n extends Mock implements FlutterI18n {}

void main(){
  FlutterI18n i18n;

  setUp((){
    i18n = MockI18n();
  });

  test('should translate with key label.myWidget.title', () {
    // setup
    
    verify(i18n.translate(any, 'label.myWidget.title');
  });
}
```

Thanks!

**Comment by ilteoood** [comment]
Hi @moseskarunia,
we don't have any plan for this kind of conversion.
Did you take a look to our test suite? IMO to achieve what you need is sufficient to create a mocked translation loader.

Please, take a look here:
https://github.com/ilteoood/flutter_i18n/blob/master/test/test_widget.dart

**Comment by moseskarunia** [comment]
Hi @ilteoood thanks for the reply. I want to ask a follow up question then. If I make it like this, is there any pitfall I should be wary of? Like the new language won't get loaded if it's changed during app run, or something. Thanks!

**Comment by ilteoood** [comment]
Currently I don't know, but this is not the way that I imagined...

**Comment by moseskarunia** [comment]
> Currently I don't know, but this is not the way that I imagined...

ok. thanks. 

In case someone stumbled upon this thread, my solution is to build wrapper around translate, and make the wrapper as a dependency of my widgets.

```dart
class Translator {
  const Translator();

  String translate(
    final BuildContext context,
    final String key, {
    final String fallbackKey,
    final Map<String, String> translationParams,
  }) =>
      FlutterI18n.translate(context, key,
          fallbackKey: fallbackKey, translationParams: translationParams);
}
```
