### ISSUE TITLE
Supporting i18next format

### ISSUE THREAD

**Issue by Amir-P** [ilteoood/flutter_i18n#154]
Hello,
Do you have any plans on supporting [i18next](https://www.i18next.com/misc/json-format) format?

**Comment by ilteoood** [comment]
Currently not, but I could plan it

**Comment by Amir-P** [comment]
I was thinking of working on it since I really need it in a project. So it's ok with you to change current supported JSON format in this plugin?

**Comment by ilteoood** [comment]
You could try, but both versions should be supported.
It is a huge work, I have to think about the structure of the library
