### ISSUE TITLE
make it possible to directly access the loaded translations

### ISSUE THREAD

**Issue by AlexShniperson-INO** [ilteoood/flutter_i18n#164]
i mean this line of code
https://github.com/ilteoood/flutter_i18n/blob/master/lib/flutter_i18n.dart#L31

something like
```
FlutterI18n.getDecodedMap(context)
```
i need that because i need to manipulate with keys

**Comment by ilteoood** [comment]
This won't happen.

That map represents the internal state of the library: I'm now using a map, but I can switch to any other data structure and for the user this must be transparent.
