### ISSUE TITLE
ICU format 

### ISSUE THREAD

**Issue by jasin755** [ilteoood/flutter_i18n#165]
I have started use this library. But I found a problem with ICU formats like:
```
{
   "key3":"{count, plural, one {gift} few {gifts} other {gifts} }"
}
```
does it implemented? 
Thanks.

**Comment by ilteoood** [comment]
This syntax isn't implemented.

The available syntax is this:
https://github.com/ilteoood/flutter_i18n/blob/master/CHANGELOG.md#040
