### ISSUE TITLE
black screen that shows up between the LaunchImage and my app's first screen

### ISSUE THREAD

**Issue by jlcool** [ilteoood/flutter_i18n#17]
when customize launch splash screen

**Comment by ilteoood** [comment]
Why this be fault of interest flutter_18?

**Comment by jlcool** [comment]
I tried not to use flutter_i18n. No problem. I found that load in FlutterI18nDelegate is the reason of async method. My English is not good. I don't know if I can explain it clearly.

**Comment by ilteoood** [comment]
Sorry, but without an example or a concrete analysis I don't know where to begin.

**Comment by jlcool** [comment]
you can try this https://github.com/jlcool/flutter_app_qidongye (android)  and  I found that load() in FlutterI18nDelegate is the reason of async method

**Comment by jlcool** [comment]
Android only needs to configure launch_background.xml and flutter_i18n to have this problem. IOS I didn't try.

**Comment by blntylmn** [comment]
This is really happens when I add `FlutterI18nDelegate` in `localizationsDelegates`.. Without `FlutterI18nDelegate` there is no black screen..

**Comment by ilteoood** [comment]
Can you modify the example the reproduce this problem?

**Comment by blntylmn** [comment]
Here:
[https://github.com/blntylmn/flutter-splash-screen](url)

uncomment line `20` and `26` in `main.dart`
and comment lines `27` to `31`

you will see the black screen appears.

**Comment by ilteoood** [comment]
For "black screen" you mean that < 10ms image that preceed the ScreenOne?

**Comment by blntylmn** [comment]
Nope.. 
There is 1 to 4 second `empty black screen` between `splash screen` and `ScreenOne`. You can see it much well on android emulator..

**Comment by ilteoood** [comment]
Use the 0.6.3 version and consider to modify your example as follow:

`import 'package:flutter/material.dart';
import 'package:flutter_i18n/flutter_i18n_delegate.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'screen_one.dart';
import 'screen_three.dart';
import 'screen_two.dart';

var router = <String, WidgetBuilder>{
  "/screen-2": (BuildContext context) => ScreenTwo(),
  "/screen-3": (BuildContext context) => ScreenThree(),
};

Future main() async {
  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
      useCountryCode: false, fallbackFile: 'en', path: 'assets/locales');
  await flutterI18nDelegate.load(null);
  runApp(MaterialApp(
    title: 'Splash Screen',
    theme: ThemeData(
      primaryColor: new Color(0xff622f74),
      accentColor: Colors.orange,
    ),
    localizationsDelegates: [
      flutterI18nDelegate,
      GlobalMaterialLocalizations.delegate,
      GlobalWidgetsLocalizations.delegate
    ],
    home: ScreenOne(),
//      home: Scaffold(
//        body: Center(
//          child: Text('Test'),
//        ),
//      ),
    routes: router,
  ));
}
`

**Comment by blntylmn** [comment]
You are aggressively closing all issues whether is solved or not.
Your solution is not working. (yes I installed 0.6.3)
I tried every possible solution but none of them helped. Like below one :
```
Future main() async {
  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
      useCountryCode: false, fallbackFile: 'en', path: 'assets/locales');
  runApp(SplashScreen());
  flutterI18nDelegate.load(null).then((onValue) {
    runApp(MaterialApp(
      title: 'Splash Screen',
      theme: ThemeData(
        primaryColor: new Color(0xff622f74),
        accentColor: Colors.orange,
      ),
      localizationsDelegates: [
        flutterI18nDelegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
      supportedLocales: [const Locale("en"), const Locale("tr")],
      debugShowCheckedModeBanner: false,
      home: ScreenOne(),
      // home: Scaffold(
      //   body: Center(
      //     child: Text('Test'),
      //   ),
      // ),
      routes: router,
    ));
  });
}
```
I tried other JSON solutions as well. (like easy_localization)
The problem is when loading delegates waiting for JSON file loading and this causes between splash screen and app screen a black screen.
So I decided to turn back Intl solution. It is a bit hard to maintain and yes it is boring but it works perfect.
No black screen no cry :)
Thanks for your effort btw.

**Comment by ilteoood** [comment]
The problem with your code is that you are doing an async task inside the runApp method. This cause the app to hang and wait the rources to be loaded. 
I've tried your example on both android emulator and genymotion, and with the new version the blank screen isn't happening. 
I can make you a screen record to prove that but, fortunately, isn't a my problem anymore :)

**Comment by blntylmn** [comment]
I tried your suggestion exactly how you write nothing changed then i tried other things..
Anyway you will hear more from this issue in the near future from others. Because it is not working well splash screen and JSON localization together.

**Comment by ilteoood** [comment]
The only thing that I can suggest is to do a Flutter get, flutter upgrade and then a Flutter clean to be sure that you aren't using and old apk build.
Are you @jlcool facing this issue again with the latest version and the example provided above?

**Comment by Purus** [comment]
When `main()` is async, I had the same issue of black screen in the first few frames.

But following the solution provided, the issue is resolved. I can confirm on the same.

**Comment by ilteoood** [comment]
Thank you so much for your contribute, really appreciated!

**Comment by jlcool** [comment]
It's finally repaired.I've been using https://github.com/ilteoood/flutter_i18n/pull/18

**Comment by chaunqingren** [comment]
I have the same problem. Thank you for your contribution.
