### ISSUE TITLE
How can I handle internationalization of different scriptCode?

### ISSUE THREAD

**Issue by danielchan303** [ilteoood/flutter_i18n#171]
I have have to show traditional Chinese, or simplified Chinese based on user preference. This is in the scriptCode part of the Locale but not the countryCode, how I can show the correct language to the user?

**Comment by ilteoood** [comment]
Hi, currently is not supported because the script part is ignored

**Comment by ilteoood** [comment]
Support inserted and documented: you can use the `useScriptCode` parameter to enable it!
