### ISSUE TITLE
Non-fatal Null check operator Exception

### ISSUE THREAD

**Issue by apastuhov** [ilteoood/flutter_i18n#176]
Hi, I've got next Non-fatal error in crashlytics:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at SimpleTranslator._decodeFromMap(SimpleTranslator.java:50)
       at SimpleTranslator._translateWithKeyFallback(SimpleTranslator.java:42)
       at SimpleTranslator.translate(SimpleTranslator.java:24)
       at FlutterI18n.translate(FlutterI18n.java:107)
       ...
```

flutter_i18n: ^0.30.0

Translation file is loaded from network via
```dart
NetworkFileTranslationLoader(
      baseUri: Uri.https('website.com', 'i18n/'),
      decodeStrategies: [JsonDecodeStrategy()],
)
```

According to app logs it seems that app started, but translations were not loaded yet - but app tries to get translation and plugin fails with `Null check operator`.

Looking into the source code of the plugin I have a feeling that it is related to the next lines of `SimpleTranslator`:
```dart
  String? _decodeFromMap(final String key) {
    final Map<dynamic, dynamic> subMap = calculateSubmap(key)!;
    // ...
  }

  Map<dynamic, dynamic>? calculateSubmap(final String translationKey) {
    // ...
```

So it cannot assign `Map<dynamic, dynamic>?` to `Map<dynamic, dynamic>`. But I am not sure if it is a real root cause of the issue.
Also, after translations are loaded from network - everything is working as expected ;)

Thanks!

**Comment by ilteoood** [comment]
Hi!
Are you using the `ensureInitialized` method to wait the full loading of the widget?

**Comment by ilteoood** [comment]
Ping @apastuhov

**Comment by ilteoood** [comment]
Closed for inactivity
