### ISSUE TITLE
Migrate example to sound null safety

### ISSUE THREAD

**Issue by vkammerer** [ilteoood/flutter_i18n#177]
Hello and thank your for the library.

We are trying to adapt your example to our our codebase but it currently isn't compatible with a project running on null safe dart.
For example, the line https://github.com/ilteoood/flutter_i18n/blob/master/example/lib/network_example.dart#L27 isn't valid, since the `Locale` parameter to `.load` is not nullable.

Would it be possible to migrate the example to null safe dart?

**Comment by ilteoood** [comment]
Closed with the latest commit
