### ISSUE TITLE
Only default and one language working

### ISSUE THREAD

**Issue by fun-daz-dig** [ilteoood/flutter_i18n#178]
As I set up the plugin, I realized that the current locale always was "en" in my case and I could not change or manipulate it.

Was developing on chrome.

Got it to work with the following addition/solution.

https://stackoverflow.com/questions/67921094/flutter-get-current-time-zone-code-name-is-always-en-us

I don't know If I did something wrong at the beginning or later, but it works now. 

Might be interesting for someone having the same issues.

Might also be missing in the setup description of this plugin.

**Comment by ilteoood** [comment]
Hi,
Do you want to open a PR, in order to insert this tip in the Readme?

**Comment by fun-daz-dig** [comment]
yes I can do that. but I wanna know if I am the only one who needed that adjustment. And why didn't anybody else run into this behavior... so does it also work without the suggested solution to the problem? does this only happen for chrome? I don't know ...

**Comment by ilteoood** [comment]
When I introduced the compatibility I haven't found any needs to insert the supported languages.
Is it working for you the example provided in this demo?

Usually, the supported languages should be specified only for iPhones.

**Comment by ilteoood** [comment]
Ping @fun-daz-dig

**Comment by fun-daz-dig** [comment]
i was using it on iPhone Simulator and I had the above described problems, after adding the supported languages it worked just fine. Didn't know it was only necessary for iPhones. I don't know what your intention is/was not to include this property? You decide if you want that to be added in readme. :)
