### ISSUE TITLE
Set appropriate log levels

### ISSUE THREAD

**Issue by vkammerer** [ilteoood/flutter_i18n#179]
Hello and thank you for the package,

This issue was already raised in https://github.com/ilteoood/flutter_i18n/issues/129 but not addressed.

The plugin currently logs a lot of "non actionable messages". This has the unfortunate effect of hiding other important logs in a sea of non actionable ones. The flutter style guide has a dedicated section about this topic: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#only-log-actionable-messages-to-the-console

Looking at the current implementation of the [`MessagePrinter`](https://github.com/ilteoood/flutter_i18n/blob/8c48c9c6de60d5dd1f6157b2934086df2d4ce57d/lib/utils/message_printer.dart) class, it looks like it could take advantage of [`logging`](https://github.com/dart-lang/logging) (dart core package) or [`logger`](https://github.com/leisim/logger) to set appropriate log levels.

If most current logs are moved to a verbose level, it will make the warnings and errors stand out more.

**Comment by ilteoood** [comment]
That's really interesting. I'll take care to make it better.

As usual, PRs are welcome 😁

**Comment by ilteoood** [comment]
This has been fixed with the latest commit.
I'll release a new version soon.

**Comment by vkammerer** [comment]
Thank you @ilteoood. I see you've changed your logging class and prepared everything for a new version. Is there still something that keeps you from publishing it?

**Comment by ilteoood** [comment]
Hi @vkammerer,
nope! I've released it.
