### ISSUE TITLE
Support function for NetworkFileTranslationLoader URL

### ISSUE THREAD

**Issue by lwansbrough** [ilteoood/flutter_i18n#180]
I'd like to be able to define my URL exactly (we use our own API and cannot support `/en.json` at the end of the URL.) If I could pass in a URL template `string Function(string, string)` which would pass in the language and country codes and output a full URL, that would be ideal.

**Comment by ilteoood** [comment]
Hi @lwansbrough,
IMO this is a too much custom extension to be included in NetworkFileTranslationLoader.

BTW, I suggest to create a custom loader that extends NetworkFileTranslationLoader: you can create your own or make a PR for it, it's up to you! :)

Let me know

**Comment by ilteoood** [comment]
Ping

**Comment by lwansbrough** [comment]
We may consider that option, seems fairly reasonable (though I dispute that having a custom URL format should be out of scope.) Currently exploring using the official library as another option. Thanks for your response!
