### ISSUE TITLE
Is it possible to return different translation when param is missing?

### ISSUE THREAD

**Issue by harkairt** [ilteoood/flutter_i18n#182]
I'd like to have a welcome message.
If param is specified then it should return `Welcome Bob!`, but if param is missing/null, it should return `Welcome!` (notice the `!` without the space after the parameter). 
Right now what I can achieve is `Welcome !`

**Comment by ilteoood** [comment]
You can achieve that using 2 different translation keys and using the null check to choose what to display.
Am I missing something?
