### ISSUE TITLE
Flutter Web: Error: Unsupported operation: Platform._version

### ISSUE THREAD

**Issue by connectprabhjeet** [ilteoood/flutter_i18n#184]
Unable to use flutter_i18n on web but pub.dev shows it is supported for web. Looks like problem with` NetworkAssetBundle`.

<img width="792" alt="Screenshot 2022-01-15 at 5 45 26 PM" src="https://user-images.githubusercontent.com/53077577/149621519-9a976d5f-9432-485e-98f4-377cb137eedb.png">

**Comment by ilteoood** [comment]
Fixed with version 0.31.1
