### ISSUE TITLE
NetworkFileTranslationLoader fetches locale twice

### ISSUE THREAD

**Issue by connectprabhjeet** [ilteoood/flutter_i18n#185]
While using `NetworkFileTranslationLoader`, loader calls locale/en.json twice.

<img width="317" alt="Screenshot 2022-01-15 at 6 11 00 PM" src="https://user-images.githubusercontent.com/53077577/149622070-759b9da5-b534-4706-8d6d-8a60ddc1ee7d.png">

**Comment by ilteoood** [comment]
Fixed with version 0.36.2
