### ISSUE TITLE
Language from previous page will not change when i refresh locale in current page

### ISSUE THREAD

**Issue by quocviet1996** [ilteoood/flutter_i18n#201]
Hi!, Thanks for great package. Unfortunately I'm having a problem with this . For example i  tested with route from page A->move to  page B, then from B i've run refresh function to change lang, this B page automatically change lang perfectly, but when i go back to the A page, the lang doesn't change.  Is there is a bug or it don't support change the lang for the whole app when changing from any page or it's just because i've something wrong with my code :)). Thanks very much

**Comment by ilteoood** [comment]
Hi, I think that this happens because nothing in your previous page trigger a re-render for the new translated strings.

I'll take a look at it

**Comment by quocviet1996** [comment]
> Hi, I think that this happens because nothing in your previous page trigger a re-render for the new translated strings.
> 
> I'll take a look at it

Wow, thanks for the quick reply, will try with you tomorrow :))

**Comment by ilteoood** [comment]
Closing as in stale
