### ISSUE TITLE
Upgrade intl package to 0.18.0

### ISSUE THREAD

**Issue by romgrm** [ilteoood/flutter_i18n#204]
Hi ! 

Thanks for this package, its very useful. 
Could you just update the intl package from 0.17.0 to 0.18.0? 
This causes conflicts in some projects. 

Thank you very much

**Comment by ilteoood** [comment]
Unfortunately, I can't.

A test depends on flutter_localizations wich has pinned version 0.17.0: https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml#L11

You should open an issue there first.

**Comment by ilteoood** [comment]
> looks like they upgraded it already

It is not available in stable release yet

**Comment by benoit-rolandeau-act** [comment]
> > looks like they upgraded it already
> 
> It is not available in stable release yet

Hello,

It appears it is in master now (I have now conflicts with the last stable version of flutter)

**Comment by fabios9702** [comment]
update on this?

**Comment by cpuell** [comment]
I think it is now upgraded. Can we get this upgraded please?

**Comment by ilteoood** [comment]
This should be closed with version 0.33.0
