### ISSUE TITLE
Fallback for single translation

### ISSUE THREAD

**Issue by HeidemannMarkus** [ilteoood/flutter_i18n#21]
Hey ho,

thanks for providing that cool package.

I have currently two languages in my app.
Main language german and secondary english.

The english language file does miss some translations.

Is it possible to fall back to the "fallback-file" in the context of a single translation?

**Comment by ilteoood** [comment]
Nope, it's not possible.
The fall back is the translation key

**Comment by HeidemannMarkus** [comment]
Thank you for the quick response! 

I had a quick lock into it and I see an dirty soloution: 
- load the fallbackLanguageFile 
- at any time a translation is not found (aka. null -> l. 85 `if (translation == null) {` in `flutter_i18n.dart`)
- load backup-language file / translations and add the missing translation to the `decodedMap`
  - or initally load the backup-language into ~`decodedMap-backupLanguage` and query this language 
  - and only if there is no translation found return the key


--- 

Would this be an accetable solution for you to merge?

**Comment by ilteoood** [comment]
The load of the fallback file is an expensive operation in terms of time and memory consumption.
Remember that the fallback file will be used only when there isn't any translation file defined for the user's system language.

It's always better to keep the two maps with the same data.

**Comment by SvenSchoene** [comment]
I'd love to have this feature as well. It was quite helpful for us in a previous application where we had fallbacks to another language for specific missing keys in Laravel.

On the other hand Laravel renders pages during build time and does not have to keep all language strings in memory for the user, so I fully understand your concern, @ilteoood . However, this is the only feature missing and it would be nice to have.

If this is actually a deal breaker and I figure out a way to implement this in this package, I'll offer up a Merge Request. No worries: if you don't think it's a feature worth having in the library, just close it, no bad feelings. :)

In any case: this is a great and easy-to-use library for translation. Thanks for creating and sharing it!
