### ISSUE TITLE
Using NetworkFileTranslationLoader breaks DeepLinks with GoRouter (When app is totally closed) on iOS

### ISSUE THREAD

**Issue by jarriaza-102** [ilteoood/flutter_i18n#211]
I'm testing an application that is using `Material.router` with `GoRouter` configuration, it works just fine with its default configuration.
But whenever I start using `FlutterI18nDelegate` in the `localizationDelegates`
```
 MaterialApp.router(
  localizationsDelegates: [
    FlutterI18nDelegate(
      translationLoader: NetworkFileTranslationLoader(
        baseUri: Uri(
          scheme: 'https',
          host: host,
          path: path,
          queryParameters: queryParameters,
        ),
        useCountryCode: false,
      ),
    ),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate
  ],
  supportedLocales: const [
    Locale('en'),
    Locale('es'),
  ],
  title: 'Hype',
  routerConfig: router,
)
```
The deep links when the app is totally closed stopped to work.
I mean if you use a deep link as follows:
`xcrun simctl openurl booted https://google.com/details` it works just fine when app is running
If you close the app and runs it, the deeplink doesn't work, it just opens the app,
I'm guessing that it's because of the INTL because when I get rid of the `FlutterI18nDelegate` it works fine.
I'm also not sure if that's expected as it should wait for the file to be available before running the app at all.

It works fine on Android

**Comment by ilteoood** [comment]
What was the issue?

**Comment by jarriaza-102** [comment]
> What was the issue?

It was only on emulator I guess, on a real device it works fine
The issue was that when the app is 100% closed in iOS, you have localizations with Network, and you're using deeplinks.
Whenever you fire a deeplink action, the app is opened but doesn't navigate to the deeplink location
But it works on a real device.
