### ISSUE TITLE
Compatibility Issue with http 1.1.0

### ISSUE THREAD

**Issue by floherzler** [ilteoood/flutter_i18n#212]
I encountered a dependency conflict related to the `http` package version. The current version depends on `http: ^1.1.0`, which led to incompatibility with other packages in my project that require `http: ^1.0.0`.

### Specifics
- `flutter_i18n` version: 0.34.0
- Conflict with: `appwrite` (requires `http: '>=0.13.6 <1.0.1'`)
- Error encountered: Version solving failed due to incompatible `http` versions.

### Temporary Solution
Forked `flutter_i18n` and modified the `http` dependency to `http: 1.0.0` to resolve the conflict. This worked successfully with my project setup, including an upgrade to `appwrite` version 11.

I talked to an Appwrite dev and he told me they want to keep supporting older versions and there are not including `http: ^1.1.0`.

I didn't open a PR since fixing the version of `http` didn't seem like a good solution for everybody.

If you want me to open a PR I'd be happy to do that though, just leaving it here if someone needs to see it!

**Comment by ilteoood** [comment]
Instead of forking, you could use one of the older versions of the library.
I'll not downgrade http, as it could cause issue with other apps.
