### ISSUE TITLE
Additional "assets/" added to path on each local refresh (Web)

### ISSUE THREAD

**Issue by apiornoIA** [ilteoood/flutter_i18n#213]
Hi, i am facing an issue while trying to refresh local on Web release mode.

`FlutterI18n.refresh(context, Locale(localString));`

Every time this refresh line is execute it adds an extra "assets/" to the path, generating "assets/assets/assets/i18n/.."

I saw there is a class I18nWeb but it does not have any behavior, is there any way to handle all this?

**Comment by ilteoood** [comment]
Unable to reproduce it
