### ISSUE TITLE
Having both a translation key and object

### ISSUE THREAD

**Issue by AlexBolot** [ilteoood/flutter_i18n#214]
Hi, 

I encountered a use-case that I can't seem to solve yet !
I receive some key-base content, that I need to translate. This is the keys format : 

```
reporting.bus_stop.update
reporting.bus_stop.update.status
reporting.bus_stop.update.status.done
```
The issue is that it would require this JSON, which is of course invalid: 

```
"reporting" : {
  "bus_stop" : "My title",
  "bus_stop" : {
    "update" : "Update title",
    "update" : {
      "status" : "Status title",
      ...
    }
  }
}
```

Any way I could make this work ? I've tries alternatives but with no success...

**Comment by ilteoood** [comment]
The data source should always be valid, you should move the title inside the object
