### ISSUE TITLE
Upgrade intl package to 0.19.0

### ISSUE THREAD

**Issue by clementdemily** [ilteoood/flutter_i18n#217]
Hello !

First of all, thanks for this package. I'm using it since I started playing around with flutter and I find it really useful !

I recently add notification support for my app, using the wonderful library `awesome_notifications`, but I seems like I can't get the latest version of it, because they rely on the latest version of `intl` package. It can possibly affect other library that I don't personally use.

```
Because awesome_notifications >=0.8.3 depends on intl ^0.19.0 and flutter_i18n 0.35.0 depends on intl ^0.18.1, awesome_notifications >=0.8.3 is incompatible with flutter_i18n 0.35.0.
And because no versions of flutter_i18n match >0.35.0 <0.36.0, awesome_notifications >=0.8.3 is incompatible with flutter_i18n ^0.35.0.
So, because tale_me depends on both flutter_i18n ^0.35.0 and awesome_notifications 0.9.2, version solving failed.
```

Is it possible to update the intl package from 0.18.1 to 0.19.0 for the next release ?

Thank you !

**Comment by yelkamel** [comment]
Hello same issue for me please upgrade the intl in the package so we can use it :)

**Comment by clementdemily** [comment]
@yelkamel In the meantime, If you want, you can force `intl` to version `0.19.0` by adding these lines to your `pubspec.yml` file. 

```yaml
dependency_overrides:
  intl: 0.19.0
```

I got no issue on my side, all my tests passes but I don't use all the features provided in this package. It should be fine since no breaking changes were listed on `intl` package's changelog.

**Comment by ilteoood** [comment]
Version 0.35.1 should fix this, please let me know
