### ISSUE TITLE
support array and list

### ISSUE THREAD

**Issue by Judimax** [ilteoood/flutter_i18n#218]
In relation to the earlier issue here opened a few years back
https://github.com/ilteoood/flutter_i18n/issues/142
This necessary for my use case because in angular ngx-translate arrays are allowed. I rather keep the large json files in sync instead of have to make more or a burden for myself

**Comment by Judimax** [comment]
Greetings I gave it a PR
https://github.com/ilteoood/flutter_i18n/pull/219

**Comment by ilteoood** [comment]
As said, this is already achievable using a different syntax.
