### ISSUE TITLE
Translations are not updated when locale attribute in MaterialApp changes

### ISSUE THREAD

**Issue by Quijx** [ilteoood/flutter_i18n#22]
As we have discussed a little bit here: https://github.com/ilteoood/flutter_i18n/issues/16#issuecomment-468932480
the reason for this bug is that the translations are not chosen by the `locale` parameter inside the `load` method of the `LocalizationsDelegate`.

As reason why you don't do this you wrote:
> The reason why I don't use the LocalizationsDelegate is to leave the possibility to override the fallback settings of the device (eg: English for everyone, even if the fallback language is Spanish).

However, the fallback language can be controlled by setting a custom `localeResolutionCallback` in the `MaterialApp`.
I think what you described could be implemented like this:

```
localeResolutionCallback: (preferredLocale, supportedLocales) {
    if (supportedLocales.contains(preferredLocale)) {
        return preferredLocale;
    }
    return supportedLocales.first;
},
```

Example:
If your `supportedLocales` are English and Spanish  
`supportedLocales: [Locale('en'), Locale('es')]`
and your system locale preferences are:  
1. Italian
2. Spanish
3. English

then the callback would choose English, while without it Spanish would be chosen.

If the whole preference list is needed to choose the fallback manually, `localeListResolutionCallback` can be used.

As a second reason you gave:
> Also, with this approch, the entire widget tree isn't reloaded when the system language change.

I believe this happens regardless.
https://flutter.dev/docs/development/accessibility-and-localization/internationalization  
states that:
> The `Localizations` widget defines the locale for its child and the localized resources that the child depends on. The `WidgetsApp` widget creates a `Localizations` widget and rebuilds it if the system’s locale changes.

And even if not, changing the language doesn't happen every second, so this wouldn't be a big deal.

So I propose the following changes:
1. Remove `FlutterI18n.refresh` because intended way to control the language manually is via the `locale` attribute of `MaterialApp`.
2. Remove the fallback in the `FlutterI18nDelegate` because you can control the fallback arbitrarily with `localeResolutionCallback` or `localeListResolutionCallback`.
3. Choose the selected locale/language of `FlutterI18n` only by the `locale` in the `load` method of the `FlutterI18nDelegate` that creates the `FlutterI18n` object.

---

**Side node:**
Also I was wrong when I wrote  
> And when the locale is selected in this way, getting the current locale is really useful because I think the only alternative would be to create a custom Delegate that stores the locale somewhere when load is called.

Apparently `Localizations.localeOf(context)` can be used to get the currently selected locale. I guess this would make `FlutterI18n.currentLocale` redundant.

**Second side note:**
I think translating keys should be done with `FlutterI18n.of(context).translate('key')` not with `FlutterI18n.translate(context, 'key')` because it is more standard. But that's just preference... Maybe have both so that existing code doesn't break?

**Comment by ilteoood** [comment]
Hi,
thank you for your analysis.
What you say initially is correct, I could use a localeResolutionCallback but...I don't want to.
I explain myself: I don't want to force anyone to wrote the supportedLocales list; this is one of the bullet point for which I created this library.
You don't have to write the supportedLocales list because you have already "explicited" it placing your .json inside the assets folder.

For the second part, it's true that the language doesn't change every second, but the subtree is re-generated every time that (for example) you just turn your device. Your example code will force the load method to regenerate the Map<String, any>, even if it's already loaded.

BTW, I think I have a solution for this.

**Comment by Quijx** [comment]
I think trying to not use `supportedLocales` to make it localization simpler achieves the exact opposite. While it will result in less code, it reduces flexibility and teaches the user a non standard way. If the user needs to switch for example to Intl at some point because json is not powerful enough anymore, he has to relearn how to switch language, customize fallback language and use `supportedLocales`. Also it makes it harder to use for people who have used different translation libaries in the past.

The first site everybody looks at when trying to internationalize an app is probably this one:
https://flutter.dev/docs/development/accessibility-and-localization/internationalization
Here the `supportedLocales` and even `localeResolutionCallback` is explained.
And I think trying to teach the user a completely different way that may seem simpler at first is just not helpfull in the long run.

Also, writing the `supportedLocales` takes maybe a minute, and you don't add new languages all the time, so I don't think it's a big deal.

And my idea for the second part is to load the `Map<String, any>` in the delegate and pass it to the `FlutterI18n` class in the constructor. But maybe you had the same Idea :)
