### ISSUE TITLE
Non-ASCII characters are not displayed correctly

### ISSUE THREAD

**Issue by chamartt** [ilteoood/flutter_i18n#229]
Hi,

Since Flutter/Pods/Pub updates, all our non-ascii characters are not displayed correctly anymore.

For exemple, emojis are not displayed anymore and accented characters like "é" are displayed as "Ã©".

We are using network json files, which are working correctly for our production release (which is with the non up-to-date Flutter version)

Files have not been updated, and are in UTF-8 without BOM.

We didn't touch the plugin initilization which is:

`final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
      translationLoader: NetworkFileTranslationLoader(
        useCountryCode: false,
        fallbackFile: 'fr',
        forcedLocale: locale,
        baseUri: Uri.https([OUR SERVER], "translations"),
        decodeStrategies: [JsonDecodeStrategy()],
      ),
    );
`

It look like encoding issue, but I don't know how to fix it.

Thanks in advance for your help.

**Comment by ilteoood** [comment]
I have tried using the `example` application provided here.
Emojis and accented letters are displayed correctly.

Without a proper repro, I can only close it.

**Comment by chamartt** [comment]
@ilteoood 

Thanks for testing.
Can you share me your file conf encryption like UTF-8, BOM ; please ?

**Comment by ilteoood** [comment]
You can find it in the folder example within this repo

**Comment by chamartt** [comment]
For information, the problem was about the type of my Firebase Storage that was only application/json
By setting it with application/json; charset=utf-8, the problem dissapears.

Thanks anyway !
