### ISSUE TITLE
Default language is always the same if I have two selected in device

### ISSUE THREAD

**Issue by NathanAP** [ilteoood/flutter_i18n#23]
Hi! Thanks for all your effort with this package! Unfortunately I'm having a problem in my tests with iOS platform. My supported locales in main are 'en' and 'pt' with this delegate: `FlutterI18nDelegate(useCountryCode: false, path: 'assets/i18n', fallbackFile: 'en')`. I have three situations in my tests:

1. System with only one of those languages selected brings the correct language.
2. System with another language selected brings the correct fallback language.
3. System with English and Portuguese language selected always brings Portuguese. I wish I could bring the default system language, not the region.

Something I notice is that I keep getting a return of 'en_BR' (English as default) if I do `print(FlutterI18n.currentLocale(context));` in situation 1,  'es_BR' (Spanish as default) if I'm in situation 2 and 'pt_BR' (English as default but Portuguese available) if I'm in situation 3.

Sorry if I'm doing something wrong, but I read the documentation and could not find anything that could help me.

**Comment by ilteoood** [comment]
Hi,
When you have two selected languages, which is the main one on the system?
Can you also share the declaration of the supported locales? I haven't inserted in any of the example because with this library you don't need them.

Thanks,
Matteo

**Comment by NathanAP** [comment]
If I select Portuguese or English as default the result is the same, always Portuguese. I'm from Brazil, so I believe it is looking for my region.I  also tried change my region to US and I always get English, even when I change to Portuguese as default.

I'm declaring directly inside my MaterialApp like this:
`supportedLocales: const <Locale>[
  Locale('en'),
  Locale('pt')
]`

**Comment by ilteoood** [comment]
Can you reproduce it with Android, or is it an iOS-only bug?

**Comment by NathanAP** [comment]
Sorry for late reply. I can reproduce on iOS but the latest version of Android works pretty well.

**Comment by ilteoood** [comment]
Can you try with the new version and tell me if something changed?

**Comment by NathanAP** [comment]
Hi! Sorry, I could test only this morning with a Mac in an iOS device. I'm getting an error `The getter 'forcedLocale' was called on null` in the very first screen of my project with the same code after updating my pubspec.yaml to 0.6.1. Is there something I could do to fix it?

**Comment by ilteoood** [comment]
How are you using it?
I think that this happen when the delegate hasn't finished to load the assets. On my example project I can't reproduce it.

**Comment by NathanAP** [comment]
I'm actually using as before... If I rollback to 0.6.0 it works fine. I'm using this inside my MaterialApp:
`supportedLocales: const <Locale>[`
 `Locale('en'),`
` Locale('pt')`
`]`
`localizationsDelegates: <LocalizationsDelegate<dynamic>>[`
`FlutterI18nDelegate(useCountryCode: false, path: 'assets/i18n', fallbackFile: 'en'),`
 `GlobalMaterialLocalizations.delegate,`
 `GlobalWidgetsLocalizations.delegate`
`]`

**Comment by ilteoood** [comment]
Can't reproduce.
Are you using the refresh method, right? Are you sure that you are using it with  a valid BuildContext?
I think that the _retrieveCurrentInstance is returning null, right?

**Comment by NathanAP** [comment]
I'm not using .refresh, only .translate and that in my MaterialApp ): Here, I got the error and put in pastebin:

https://pastebin.com/raw/tLDU2tzZ

**Comment by ilteoood** [comment]
Try now with version 0.6.2

**Comment by NathanAP** [comment]
Okay its working now! But I'm getting Portuguese in simulator and in a real device with English as main and Portuguese as secondary language... The return of FlutterI18n.currentLocale on both is 'pt_US' (simulator default location is US and real device is Brazil).

**Comment by ilteoood** [comment]
The Localizations.localeOf method return the correct locale for your device?

**Comment by NathanAP** [comment]
The return for me with both languages is always 'pt'. If I left only English and delete Portuguese the return is 'en'.

**Comment by ilteoood** [comment]
That method is the standard way to check the current device language. If that is wrong, the result of the library is wrong too.

Sorry but for that I can't do anything.

**Comment by NathanAP** [comment]
Just to clarify, is that something I'm doing wrong or is a Flutter issue?

**Comment by ilteoood** [comment]
I think that is a Flutter issue.
The only thing that I can suggest to you is to remove the supportedLanguages: the FlutterI18N don't use it.

**Comment by NathanAP** [comment]
I'll think if it is worth to post on main Flutter git about this situation then! Thanks for your suggestion, I'll remove it. And thanks for your effort with this!

**Comment by jjonasen** [comment]
Just as a note, I'm currently having the same issue but with English as fallback and Danish if the iOS simulator (iPhone Xr) is set up for it.
I have the basic en.json as base, but have created a en_DK.json for the Danish texts. This works as a workaround at least until I need to localize for non-English countries which also need a country code.

Thanks for the package Nathan :)
