### ISSUE TITLE
FlutterI18nDelegate constructor params broken

### ISSUE THREAD

**Issue by blntylmn** [ilteoood/flutter_i18n#25]
after 0.5.2 it is not working as expexted..

**Comment by ilteoood** [comment]
Is working as expected.
From version 0.6.0 is simply changed as described in the CHANGELOG.md

**Comment by blntylmn** [comment]
Nope..
When I use like 
`FlutterI18nDelegate({useCountryCode = false, 'en', basePath = "assets/locales"}),`
it says 
`Too many positional arguments: 0 expected, but 1 found.dart(extra_positional_arguments_could_be_named)`
`Undefined name 'useCountryCode'.dart(undefined_identifier)`

**Comment by ilteoood** [comment]
That isn't the correct way to instantiate the delegate. Check the right way inside the example project.

**Comment by blntylmn** [comment]
So how to set fallback and useCountryCode. Are they gone or is there another way to set them. The readme file is not consistent with example project.

**Comment by ilteoood** [comment]
FlutterI18nDelegate(useCountryCode = false, fallbackFile='something', basePath = "something")

**Comment by blntylmn** [comment]
Tried that already
it says 
`Too many positional arguments: 0 expected, but 3 found.dart(extra_positional_arguments_could_be_named)`
I feel a bit stupid now :(

**Comment by ilteoood** [comment]
No problem here. I suggest you to do a flutter packages get and upgrade and clean your cache.
