### ISSUE TITLE
Getting keys from JSON file

### ISSUE THREAD

**Issue by d3xt3r2909** [ilteoood/flutter_i18n#26]
Hi,

really great and helpful library, thanks for that. 

Is there any way or you can implement, to expose keys from JSON file. So that we don't need to hardcode these in string parameter.

**Comment by ilteoood** [comment]
Hi, thank you so much :)
Do you mean like the intelli-sense?

**Comment by d3xt3r2909** [comment]
Hi,

yup. That would be perfect.

**Comment by gedw99** [comment]
This would mean code generating dart code for all the keys. 
If you did this you would be back at essentially the same architecture as flutter and ARB files ironically.
