### ISSUE TITLE
Loading Other Language at App Start does not reflect in UI

### ISSUE THREAD

**Issue by Purus** [ilteoood/flutter_i18n#27]
I had this issue similar to #17. But it was solved based on your suggesetion in that thread.

This black screen issue happens when loading language at app start time. Any help please?

```
  final FlutterI18nDelegate flutterI18nDelegate = FlutterI18nDelegate(
      useCountryCode: false, fallbackFile: 'en', path: 'assets/i18n');

MaterialApp(
            title: 'Blouse Designs',
            theme: ThemeData(
              primarySwatch: Colors.pink,
            ),
            home: BlouseDesignApp(),
            localizationsDelegates: [
              flutterI18nDelegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate
            ],
          );
```

And in the body, I use the below code to load the language on app start.

```
  void init() async{
    String userLanguage =
        PrefsProvider.prefs.getString("userLanguage") ?? "en";
    await FlutterI18n.refresh(context, Locale(userLanguage));
  }

  @override
  Future initState() {
    super.initState();

    init();
}
```

The app starts in default language and not in the chosen language. Once I go to different page and come back, language is changed.

**Comment by ilteoood** [comment]
Hi, can you provide a full example? On the material app I don't see the async part.

Thanks, 
Matteo

**Comment by ilteoood** [comment]
If you need assistance again, please reopen it.
