### ISSUE TITLE
Plural translation

### ISSUE THREAD

**Issue by dexcell** [ilteoood/flutter_i18n#3]
Hi, do you have plan to add plural translation function since it's a common requirement? 
instead manually using `if` keyword every time.
So when you translate, you pass the plural count into the function.

(e.g. when you pass 1, it will return 'I have one apple.' when you pass 2 it will return 'I have two apples')

Thanks

**Comment by ilteoood** [comment]
Fixed with 2c4de62c5639b95ef3db8799817d6620d3111c93
