### ISSUE TITLE
bug in pubspec.yaml?

### ISSUE THREAD

**Issue by welldone217** [ilteoood/flutter_i18n#30]
flutter:
  uses-material-design: true
  assets:
   - assets/flutter_i18n/

it show me error

E/flutter ( 6382): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets/flutter_i18n/zh_Hans.json
E/flutter ( 6382): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)

***************************************************************

flutter:
  uses-material-design: true
  assets:
   - assets/flutter_i18n/en_us.json
   - assets/flutter_i18n/zh_hans.json

this is work fine.

flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.437], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

**Comment by ilteoood** [comment]
Hi,
I think is a problem with the case of the language (zh_hans instead of zh_Hans). Can you try to rename it?

**Comment by welldone217** [comment]
@ilteoood i rename it.but the same error

Syncing files to device BLN AL40...
I/flutter (25575): **title** not found
E/flutter (25575): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets/flutter_i18n/zh_Hans.json

.the error H,not h.  i do not know why.

**Comment by ilteoood** [comment]
Can you post here the piece of code where are you using the library, and an example of the json?
Just to replicate it.

**Comment by welldone217** [comment]
Widget home = HomePage();

return MaterialApp(    
      title:APP_TITLE,
    
      theme: ThemeData(
      
        primarySwatch: Colors.blue,
      ),
      //color ： 应用的主要颜色值（primary color），也就是安卓任务管理窗口中所显示的应用颜色
      //home ： 应用默认所显示的界面 Widget
      home: home,
      //routes ： 应用的顶级导航表格，这个是多页面应用用来控制页面跳转的，类似于网页的网址 。该对象是一个 Map<String, WidgetBuilder>。
      routes: <String, WidgetBuilder>{
        '/index': (_) => home,
      },
      localizationsDelegates: [
        FlutterI18nDelegate(useCountryCode: true,fallbackFile: "zh-Hans"),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
    )



*************************************************
the homepage:

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(FlutterI18n.translate(context, "title")),

**Comment by welldone217** [comment]
now it is work .i just rename zh-Hans.json to zh-hans.json then rename zh-Hans.json. thanks .

**Comment by ilteoood** [comment]
You're welcome.
Sometimes the assets isn't copied. A clean of the project should help you!

**Comment by Darren-chenchen** [comment]
loading translation Unable to load asset: flutter_i18n/en_CN.yaml

**Comment by Darren-chenchen** [comment]
![image](https://user-images.githubusercontent.com/16269032/68190040-a3137380-ffe7-11e9-8ab3-ad624dcd07a9.png)
