### ISSUE TITLE
NoSuchMethodError:The method ‘[]’ was called on null.

### ISSUE THREAD

**Issue by qiaoshouqing** [ilteoood/flutter_i18n#31]
I found that there were two things that would happen. 
1. Ios system, zh Chinese. An error will be reported after killing the process and restart the application to translate the first string. 
2. Occasionally. Problems can occur when switching to another page. And when you get back, the entire application will be in trouble.

Can it be solved in time?

```
NoSuchMethodError:The method ‘[]’ was called on null.
Receiver:null
Tried calling:[](“motto”)
```

**Comment by qiaoshouqing** [comment]
Using the latest version 1.6.3

**Comment by ilteoood** [comment]
Hi,
Without  any code example is hard for me to replicate it.

**Comment by qiaoshouqing** [comment]
I submitted the error log. Can't the error log?

**Comment by ilteoood** [comment]
I need an example of:
- how you initialize it
- how you use it
- how you structured the assets folder

**Comment by ilteoood** [comment]
Also, did you set a fallback file?

I think that this problem is similar to #23.

**Comment by qiaoshouqing** [comment]
### init
```
    localizationsDelegates: [
        FlutterI18nDelegate(
          useCountryCode: false,
          fallbackFile: "zh",
          path: "assets/flutter_i18n"
        ),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
```

### use

In order to deal with the first error situation.
```
import 'package:flutter/material.dart';
import 'package:flutter_i18n/flutter_i18n.dart';

class LocalizationUtil {

  static String translate(BuildContext context, var key, [final Map<String, String> translationParams]) {
    try {
      return FlutterI18n.translate(context, key, translationParams);
    } catch(e) {
      print("FlutterI18n Exception:" + e.toString());
      return key;
    }
  }

}
```

```
LocalizationUtil.translate(context, "motto"),
```

### file struct

```
- assets/flutter_i18n/
- assets/flutter_i18n/en.json
- assets/flutter_i18n/zh.json
```

**Comment by ilteoood** [comment]
Seems everything fine.
Can you tell me the output of the 
- Localizations.localeOf
- FlutterI18N.currentLocale

methods?

**Comment by qiaoshouqing** [comment]
In Chinese.
flutter: Localizations.localeOf(context):en_US
flutter: FlutterI18n.currentLocale:zh_CN

**Comment by theRealBitcoinClub** [comment]
@ilteoood looks like me that i am not the only soul having issues with your documentation...

Why are you not helping this guy and take feedback seriously?

**Comment by ilteoood** [comment]
Hi,
is it happening even with version 0.6.4?
Now with a MBP, I can test it even on iOS :)

**Comment by Shakle** [comment]
I tried to use to use localeResolutionCallback to autodetect language on first launch, but it works only on android, ios has an error described in this issue. Generally it returns deviceLocale = null; And I also did not understand what for does it need a return Locale here.

localeResolutionCallback: (deviceLocale, supportedLocales) {
        if (Database.initialApplicationLanguage == null && Platform.isAndroid) {
            Database.initialApplicationLanguage = Locale(deviceLocale.languageCode);
            Future.delayed(Duration.zero,
                    () => Language.provider(context).locale = Database.initialApplicationLanguage);
        }
        return deviceLocale;
      },

**Comment by ilteoood** [comment]
I'm closing it for inactivity.
For iOS related problems on automatic locale resolution, please use https://github.com/ilteoood/flutter_i18n/issues/58
