### ISSUE TITLE
Update intl dependency

### ISSUE THREAD

**Issue by jesusrp98** [ilteoood/flutter_i18n#32]
When trying to update the `intl` dependency to the latest version, 0.15.8, flutter outputs this error message:

```
Because no versions of flutter_i18n match >0.6.3 <0.7.0 and flutter_i18n 0.6.3 depends on flutter_localizations any from sdk, flutter_i18n ^0.6.3 requires flutter_localizations any from sdk.

And because every version of flutter_localizations from sdk depends on intl 0.15.7, flutter_i18n ^0.6.3 requires intl 0.15.7.

So, because cherry depends on both flutter_i18n ^0.6.3 and intl ^0.15.8, version solving failed.
```

**Comment by ilteoood** [comment]
Hi,
intl is already a transitive dependency of flutter_i18n (as you can see from the pubspec.lock), you don't have to explicit import.
I suggest you to clean your pub-cache and try again.

**Comment by jesusrp98** [comment]
Yeah, deleting the explicit `intl` import in my `pubspec.yaml` file solves this issue.

Thanks for all.
