### ISSUE TITLE
Isn't it necessary to add this to the pubspec.yaml for the default translation to work?

### ISSUE THREAD

**Issue by theRealBitcoinClub** [ilteoood/flutter_i18n#33]
According to this documentation it is necessary to add:

flutter_localizations:
    sdk: flutter

to the pubspec.yaml

https://flutter.dev/docs/development/accessibility-and-localization/internationalization#setting-up

**Comment by ilteoood** [comment]
As you can see, flutter_localizations is already part of the library:
https://github.com/ilteoood/flutter_i18n/blob/master/pubspec.yaml
