### ISSUE TITLE
Getting errors whenever i try to use an identifier which contains a dot character: I/flutter ( 1129): text.hit_icon not found

### ISSUE THREAD

**Issue by theRealBitcoinClub** [ilteoood/flutter_i18n#35]
I was using the identifier "text.hit_icon" and it is not being found ever!

I think the dot character is the issue?!

**Comment by ilteoood** [comment]
Example of code?
Did you tried to make a project clean after the declaration of the assets?
Stacktrace?

**Comment by ilteoood** [comment]
Reade here:
https://github.com/ilteoood/flutter_i18n/issues/34#issuecomment-499237007

**Comment by theRealBitcoinClub** [comment]
Boy!!! Your are such an ignorant piece of shit!!!

So for you it is not an issue at all that a character "." leads to people trying to implement your framework being frustrated about the lack of documentation???
