### ISSUE TITLE
Use $storeName inside JSON file

### ISSUE THREAD

**Issue by JobMoll** [ilteoood/flutter_i18n#36]
Hey how can i use the $storeName in the JSON translate file?
Now it shows $storeName instead of the variable.

Thanks!

**Comment by ilteoood** [comment]
Hi,
$storeName is a key of the json?
Did you add the assets path to the pubsec.yml and clean/rebuilt the project?

**Comment by JobMoll** [comment]
Hey, 

The $storeName is a variable that I get from my server. 
I could use that in a string like this Text(‘hey check out this $storeName’)

But when I try that inside the JSON file it literally displays $storeName instead of the variable. 

If you understand what I mean 😁

**Comment by ilteoood** [comment]
Ok, you must have inside the json an entry like this:

{
suggestion: "Hey check out this {storeName}"
} 

In code, you must use the library as follow:

Text(FlutterI18n.translate(build Context, "suggestion", paramMap))

Param map is a map that contains storeName as key, and the variable value that you want to show as value.

Here is the documentation:

https://github.com/ilteoood/flutter_i18n/blob/master/CHANGELOG.md#020

**Comment by ilteoood** [comment]
Hi, any news?

**Comment by JobMoll** [comment]
yeaa i got it working like this:

 FlutterI18n.translate(context, 'noSearchResults.message',
                    Map.fromIterables(['searchInput'], ['$searchInput'])),

thanks!


I got one more question tho how can i use more than 1 variable in 1 string? can i just do this?
 FlutterI18n.translate(context, 'noSearchResults.message',
                    Map.fromIterables(['searchInput'], ['$searchInput']), Map.fromIterables(['searchInput2'], ['$searchInput2'])),

**Comment by ilteoood** [comment]
This is more a dart related question :)
Btw, use: Map.fromIterables(['searchInput', 'searchInput2'], ['$searchInput', '$searchInput2'])

**Comment by JobMoll** [comment]
Nice thankss!

This is by far the best localization plugin, keep up the good work!
