### ISSUE TITLE
How to change default locale?

### ISSUE THREAD

**Issue by changfeifan** [ilteoood/flutter_i18n#37]
Hi ! I have a question . How to change the default locale?

In example :
localizationsDelegates: [
        FlutterI18nDelegate(
            useCountryCode: false, fallbackFile: 'es', path: 'assets/i18n'),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ]
I try to change the fallbackFile but the locale is always 'en'.

thanks for answer!

**Comment by ilteoood** [comment]
Hi,
the fallbackFile is a file that will be used if there isn't any .json to support the current device locale.
If you want to force a specific locale, use the method indicated here:

https://github.com/ilteoood/flutter_i18n/blob/master/CHANGELOG.md#030
