### ISSUE TITLE
current locale is reset after hot reload

### ISSUE THREAD

**Issue by grAPPfruit** [ilteoood/flutter_i18n#41]
Hello!
I'm using this plugin for some time now. Recently I noticed, that after every hot reload my language falls back to the default english.
I reverted the version back to 5.2 with the necessary changes and there it works.

For some reason `FlutterI18n.currentLocale(context)` always returns en_US on the second call or something.

Can you have a look into it?

Thanks!

Cheers

**Comment by ilteoood** [comment]
Did you tried to rebuild the app from scratch? Btw, I'll check when I'll go back from vacation

**Comment by grAPPfruit** [comment]
Yes, I have tried that. I use this library for a while now and never had any issues before.
So I don't know why this happens but there seems to be a bug in versions 6+
Enjoy your vacation!

**Comment by ilteoood** [comment]
Hi @grAPPfruit,
I've release the version 0.6.4 that should fix this problem.
Let me know if it's still here.

Keep in touch,
Matteo

**Comment by grAPPfruit** [comment]
Thanks, it seems to work!
Great Job 👍

**Comment by stevenosse** [comment]
Hello!
i'm using this plugin (version 0.19.1) and i'm facing the same issue.

**Comment by ilteoood** [comment]
Hi @stevenosse,
can you post an usage example?

**Comment by stevenosse** [comment]
![Capture d’écran de 2020-09-02 21-05-33](https://user-images.githubusercontent.com/33069233/92031166-126d0780-ed60-11ea-875f-a72929dc7918.png)
![Capture d’écran de 2020-09-02 21-05-39](https://user-images.githubusercontent.com/33069233/92031170-1436cb00-ed60-11ea-94d1-5a90dfeaeffe.png)


I've written a little wrapper to simplify the syntax

**Comment by nicemanis** [comment]
I'm also experiencing the same issue on `flutter_i18: 0.14.0`

**Comment by ilteoood** [comment]
@nicemanis 
Hi, 0.14.0 seems a little bit old.
Can you try to update? I think that this operation doesn't require any code change.
Matteo
