### ISSUE TITLE
Feature Request: disable/enable print if key is not found

### ISSUE THREAD

**Issue by rseibane** [ilteoood/flutter_i18n#44]
Pretty cool library! Just a suggestion. 
It would be good to enable/disable the warning showed when a key is not found: https://github.com/ilteoood/flutter_i18n/blob/master/lib/flutter_i18n.dart#L142

It could be an optional parameter that is set to `true` by default.

Even cooler, to set a `Function<String> onKeyNotFound` delegate, so we can decide if we want to print, show a dialog or just ignore it.

Is there any reason to not allow this and force the prints?

**Comment by ilteoood** [comment]
Hi,
there isn't any reason to force the print: that part of code wasn't added by me :)
You can find the original request here:
https://github.com/ilteoood/flutter_i18n/pull/9

BTW, I think that a delegate is too much: I mean...is just a missing key!
I'll think about the possibility of remove that print!

**Comment by rseibane** [comment]
I think is good to keep a method to get feedback if the key is not found. My suggestion is just to have more control over the method applied.

Maybe just missing key but I don't want to show weird stuff to my users 😄 

Thank you!

**Comment by ilteoood** [comment]
Hi,
what do you think about #47?

**Comment by ilteoood** [comment]
Now, the messages are printed only if in development mode:
https://github.com/ilteoood/flutter_i18n/commit/263af6e4829008295ffca0906b0bd5a8457f4c00
