### ISSUE TITLE
Use SynchronousFuture to fix BlackSplashScreen?

### ISSUE THREAD

**Issue by liyujiang-gzu** [ilteoood/flutter_i18n#46]
Can you fix **BlackSplashScreen**(See issues [#42](https://github.com/ilteoood/flutter_i18n/issues/42)) with the solution of [Flutter i18n Plugin](https://github.com/long1eu/flutter_i18n)?
```dart
  @override
  Future<S> load(Locale locale) {
    final String lang = getLang(locale);
    if (lang != null) {
      switch (lang) {
        case "en":
          S.current = const $en();
          return SynchronousFuture<S>(S.current);
        case "zh_CN":
          S.current = const $zh_CN();
          return SynchronousFuture<S>(S.current);
        default:
        // NO-OP.
      }
    }
    S.current = const S();
    return SynchronousFuture<S>(S.current);
  }
```
Use `SynchronousFuture` to instead `async` and `await`, Change `FlutterI18nDelegate` like `S.delegate`
```dart
  @override
  Future<FlutterI18n> load(final Locale locale) async {
    if (FlutterI18nDelegate._currentTranslationObject == null ||
        FlutterI18nDelegate._currentTranslationObject.locale != locale) {
      FlutterI18nDelegate._currentTranslationObject =
          FlutterI18n(useCountryCode, fallbackFile, path);
      await FlutterI18nDelegate._currentTranslationObject.load();
    }
    return FlutterI18nDelegate._currentTranslationObject;
}
```

**Comment by ilteoood** [comment]
That's a great idea but from [here](https://api.flutter.dev/flutter/material/MaterialApp/localizationsDelegates.html), you can read: _We return a SynchronousFuture here because no asynchronous work takes place upon "loading" the localizations object._

Unfortunately, I have to do some asynchronous work: load the translation file

**Comment by chaunqingren** [comment]
> That's a great idea but from [here](https://api.flutter.dev/flutter/material/MaterialApp/localizationsDelegates.html), you can read: _We return a SynchronousFuture here because no asynchronous work takes place upon "loading" the localizations object._
> 
> Unfortunately, I have to do some asynchronous work: load the translation file

You're right. Need to load language.json before calling FlutterI18N.translate().
