### ISSUE TITLE
Can the key not found in default locale file be found in fallback file?

### ISSUE THREAD

**Issue by MacroLove** [ilteoood/flutter_i18n#47]
Hello, From the result I tested it I found out that if the key is not found in the **default** locale file, it also won't return the **fallback** locale file's value even though the key is located in the fallback file.
Can that be a feature to be implemented ;)
Thanks.

**Comment by ilteoood** [comment]
Hi,
this should be a nice feature, but I'm not sure what to do about.
The async process that load the translation json can be heavy for the application startup, and more things to load can bring the boot time to unsustainable levels.

I'll think about it, but for now thanks for the suggestion!

**Comment by ilteoood** [comment]
The fallback key has been implemented with version 0.9.0.
Let's take a look at: https://github.com/ilteoood/flutter_i18n/commit/b0132a1d6cf9b5471be863969f8e7b87817b41c8
