### ISSUE TITLE
Add an option to load a default locale inside the main function

### ISSUE THREAD

**Issue by DanielScholte** [ilteoood/flutter_i18n#49]
I'm not using country codes, but a language selector within my app.
When i restart the app, i now load the selected locale during initstate, and then use setstate to refresh the screen.
This causes both unnecessary file loading, and causes the default language to be visible for a second.
Preferably, i would set the default locale when creating an instance of FlutterI18nDelegate inside the main method.
I saw one of the (now closed) pull requests (#40 ) implemented this feature, but it unfortunately never got merged into master.

**Comment by ilteoood** [comment]
Hi,
I understand your need, I'll add this new feature with a new release (and also will fix #48)
I don't like the implementation of #40, for a simple reason: the library must manage the current system locale or the default language passed as argument. The code inside the first piece of the async main is boilerplate, and must be managed inside the plugin.

Thanks for the suggestion,
Matteo

**Comment by ilteoood** [comment]
Done! Use new version: 0.7.0
