### ISSUE TITLE
Translation with multiple fields

### ISSUE THREAD

**Issue by jesusrp98** [ilteoood/flutter_i18n#5]
At this moment a translation with multiple fields is not supported, for example:
```
String name = "Johnny";
String surname = "Appleseed";

FlutterI18n.translate(context, 'hello', name, surname);
```
In a JSON translation file:

en.json
```
{
    "hello": "Hello {0}, {1}.",
    "home": "I live in {0}, near {1}."
}
```
es.json
```
{
    "hello": "Hola {0}, {1}.",
    "home":  "Al lado de {1} vivo yo, en {0}."
}
```

The output is: "Hello Johnny, Appleseed", and "Hola Johnny, Appleseed".

The number in the translation string would indicate the index of the parameter in the function call itself.

This would we useful for the "home" example, since here, the spanish translation would pick the second parameter first, and then the first one.

Please, consider adding this :)
Thank you for your work, this packages is awesome!

**Comment by ilteoood** [comment]
Hi Chechu,
Did you take a look at the CHANGELOG.md?
https://github.com/ilteoood/flutter_i18n/blob/master/CHANGELOG.md#020

If you use the third parameter of the translate method, you can do this.
For example, your translation file will be:

{
hello: "Hello {name}, {surname}."
home: "I live in {city}, near {otherCity}."
}

For more details about this, please consider to take a look at the example folder. There you will see other way to use the library :)

Matteo
