### ISSUE TITLE
Error loading translation in v0.8.1

### ISSUE THREAD

**Issue by jesusrp98** [ilteoood/flutter_i18n#54]
After the last update, the package isn't able to locate the translations file.
It works in version `0.8.0`.
```
I/flutter ( 8175): Error loading translation Unable to load asset: assets/flutter_i18n/en.yaml
I/flutter ( 8175): Error loading translation fallback Unable to load asset: assets/flutter_i18n/en.yaml
```

It seems that it's trying to locate `.yaml` files by default, but I'm using `.json` instead.
Has something related to the default file extension changed?

**Comment by ilteoood** [comment]
I've released the version 0.8.2.
Unfortunately yesterday I merged a buggy version...
