### ISSUE TITLE
Debugging without Phones locale

### ISSUE THREAD

**Issue by tvhenrik** [ilteoood/flutter_i18n#55]
Debugging will stop several times when starting, if the phones locale is not in the app.  
The fallback is set and works as expected, it's just annoying to step through errors every time.  

**IDE:** VSCode  

**Steps to reproduce:**
1. Make sure not to have the phones locale in your locales folder.
2. Start debugging on the phone.

**Comment by ilteoood** [comment]
Hi,
This happens also with Android Studio?
Can you attach a screenshot/short video of what happen?

Thanks, 
Matteo

**Comment by tvhenrik** [comment]
Yes, the execution stops at the two lines below when checking for the json and yaml respectively so it's stopping 4 times at the start of every debug session. 
![image](https://user-images.githubusercontent.com/57008542/70150618-93508300-16aa-11ea-8bd9-49d381d0d080.png)
![image](https://user-images.githubusercontent.com/57008542/70150677-a7948000-16aa-11ea-8fed-7f4cf3874ade.png)
Researched this a bit and it looks like an issue with Dart: https://github.com/Dart-Code/Dart-Code/issues/2063.
But it might be sensible to check if the file exists before trying to read it anyway?

**Comment by ilteoood** [comment]
I've checked the documentation, there isn't any way to check if the assets exists. The catch of the exception is the only way...
