### ISSUE TITLE
Allow users to change base translations path

### ISSUE THREAD

**Issue by Avyiel** [ilteoood/flutter_i18n#6]
As the title says, it would be great if the base path for translations used an user-defined base path instead of a hard-coded value.

```dart
// in flutter_i18n.dart
static final String TRANSLATIONS_BASE_PATH;

// somewhere in `main.dart`
Flutteri18n.TRANSLATIONS_BASE_PATH = "assets/i18n";
```

**Comment by ilteoood** [comment]
Hi,

1) What is the real benefit to use that path?
2) This is not the standard way to translate.
3) i18n is a too generic path. The flutter_i18n is library-specific.

**Comment by Avyiel** [comment]
1. As I mentioned above, adherence to a standard.
2.
> The main goal of flutter_i18n is to simplify the i18n process in Flutter. I would like to recreate the same experience that you have with the **Angular** i18n: simple json files, one for each language that you want to support.
Take a look at [ngx-translate](https://github.com/ngx-translate/core). This is the default path they specify. Other [i18n](https://www.npmjs.com/package/i18n) and [l10n](https://github.com/robisim74/angular-l10n) packages also use `assets/locales/` as a base path. I guess any one of these two would be nearer to the default.
3. i18n infers internationalization. It is therefore specific to files used for that purpose. By forcing users to use a package-specific folder, you are:
- limiting their possibilities
- eventually harming integration with other packages

I guess you can change my issue to "Allow users to specify the base path" instead. Achieves the same results.

**Comment by ilteoood** [comment]
Thank you @Avyiel, this sounds much better!
Do you want to contribute to library and make that fix?
Otherwise, I'll do it ASAP.


Thank you so much for your contribute!

Matteo

**Comment by Avyiel** [comment]
@ilteoood I'd like to contribute :)

**Comment by ilteoood** [comment]
The standard one are ok :)

**Comment by ilteoood** [comment]
Version 0.5.0 released!
Thank you so much again!
