### ISSUE TITLE
Update package intl

### ISSUE THREAD

**Issue by deandreamatias** [ilteoood/flutter_i18n#64]
I installed this package but I have an error updating the intl package.

`Because flutter_i18n> = 0.0.2 depends on any flutter_localizations of sdk that depends on intl 0.16.0, flutter_i18n> = 0.0.2 requires intl 0.16.0.`

I need intl 0.16.1 because another package depends on it.
Can you update the intl dependency on flutter_i18n?
Thank you

**Comment by ilteoood** [comment]
I have to check the impact for the other users.
I suggest you [this](https://iiro.dev/2018/08/28/resolving-dart-package-version-conflicts/) as temporary fix.

**Comment by ilteoood** [comment]
I've made a check: intl is not a dependency of my library, but a dependency of flutter_localizations, the [Flutter SDK](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#setting-up).

I suggest you to update your SDK and retry.

**Comment by deandreamatias** [comment]
Thank for your answer. 
I'll read the temporary fix
