### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by shlima** [ilteoood/flutter_i18n#68]
Can we reload localization files on hot reloading hook?

**Comment by ilteoood** [comment]
Nope, the delegate load method isn't able to distinguish between hot reload and same-language reload.
In order to avoid black screen at startup and application slowdown, the last loaded translation file of the current language is cached.

**Comment by shlima** [comment]
We can use the hook https://api.flutter.dev/flutter/widgets/State/reassemble.html

**Comment by ilteoood** [comment]
AFAIK that method is available only in a widget, not in a dart class.

**Comment by shlima** [comment]
You can provide `FlutterI18n.reload()` method and example in Readme, so each user can implement this hook with root MaterialApp instance by themselves.

**Comment by ilteoood** [comment]
You can already do that, using the functions documented here:
https://github.com/ilteoood/flutter_i18n/blob/master/CHANGELOG.md#030
https://github.com/ilteoood/flutter_i18n/blob/master/CHANGELOG.md#060

`FlutterI18n.refresh(buildContext, FlutterI18n.currentLocale());`
