### ISSUE TITLE
Decoding map fails on iOS

### ISSUE THREAD

**Issue by dirkvranckaert** [ilteoood/flutter_i18n#69]
The problem is in `_findCurrentLocale()`. On my iOS simulator at least it systemlocale is`en`, then it get splitted on underscore and it ends up in an array of just one element off course. But in this piece of code it assumes that the locale index must be either 2 or 1 based on a lenght of 3 or 2 items. But this case is not handled...

Problematic code:
```
  Future<Locale> _findCurrentLocale() async {
    final String systemLocale = await findSystemLocale();
    MessagePrinter.info("The system locale is $systemLocale");
    final List<String> systemLocaleSplitted = systemLocale.split("_");
    final int countryCodeIndex = systemLocaleSplitted.length == 3 ? 2 : 1;
    return Future(() => Locale(
        systemLocaleSplitted[0], systemLocaleSplitted[countryCodeIndex]));
  }
```

So the corrected version should be something like this:
```
final int countryCodeIndex = systemLocaleSplitted.length-1;
```

This would a much easier implementation.
Is there any way around this issue for now? Cause i18n is now not working on my iOS device...

**Comment by ilteoood** [comment]
Hi @dirkvranckaert,
please take a look to version 0.10.1, now should be fixed.

Thank you for the issue,
Matteo

**Comment by dirkvranckaert** [comment]
Thanks, I'll give it a try!
