### ISSUE TITLE
Ability to change TranslationLoader

### ISSUE THREAD

**Issue by defint** [ilteoood/flutter_i18n#70]
We have a problem that translations doesn't load on the flutter driver tests.
The problem describes here: https://github.com/flutter/flutter/issues/24703

In short: flutter_i18n uses `rootBundle.loadString` which create separate isolate if translation file more than 10kb.
Can we have possibility to override or inject another `TranslationLoader` for testing purposes?

**Comment by ilteoood** [comment]
Hi @defint,
at the moment isn't possibile to change the translation load strategy.
For your problem, did you tried the solution provided [here](https://github.com/flutter/flutter/issues/24703#issuecomment-531277291)?

**Comment by defint** [comment]
Yes, it works. But I want to have generic behaviour for all tests.
Is it ok if I create pull request with my ideas? Or are you sure that is redundant functionality?

**Comment by ilteoood** [comment]
There's no problem for me. I think that is a thing that I have to do if I want to support, for example, loading of remote translation files...

**Comment by defint** [comment]
Great. So, I will close issue and prepare concept of this problem.
