### ISSUE TITLE
Dynamic change of locale at runtime at app level

### ISSUE THREAD

**Issue by dna-f** [ilteoood/flutter_i18n#75]
Hi and thanks for the great job you made :)
Here is my issue:

Inside my app I use two different ways to handle translations:
1. package:intl for "const" translations that I show on a view and that will not change
2. package:flutter_i18n for all those dynamic messages, sent by the server down to the app as a KEY, that should be translated to the local language

The app starts with the default locale or with the last one chosen by the user and stored in shared preferences.
Then, a StreamBuilder around the app view, rebuilds every time locale changes, for example if the user choose to change it from the language screen

<img width="295" alt="Screenshot 2020-03-14 at 08 26 13" src="https://user-images.githubusercontent.com/28953208/76677350-84446f80-65cd-11ea-9d31-fcb341d9ee4d.png">

This is how i setup the app:
...
      localizationsDelegates: [
        // ... app-specific localization delegate[s] here
        // provides localized strings for the app
        const AppLocalizationsDelegate(),
        // provides localized dynamic strings for the app. This should be useful to dynamically localize a key string returned from the server
        // const AppLocalizationsDynamicDelegate(),
        FlutterI18nDelegate(translationLoader: FileTranslationLoader(useCountryCode: false, fallbackFile: 'en', basePath: 'lib/l10n/dynamic')),
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        // provides localized strings and other values for the Material Components library
        GlobalWidgetsLocalizations.delegate
        // defines the default text direction, either left to right or right to left, for the widgets library
      ],
      // at startup locale will be set, based on device settings
      locale: locale != null ? Locale(locale, '') : null, // HERE IS WHERE locale changes during app rebuild
      supportedLocales: [
        const Locale('en', ''),
        const Locale('it', ''),
        // ... other locales the app supports
      ],

Everything works fine but i had to hack a few lines of the library to handle this.
These are the changes I made on version 0.11.1 

• flutter_i18n_delegate:

  @override
  Future<FlutterI18n> load(final Locale locale) async {
    MessagePrinter.info("New locale: $locale");
    if (FlutterI18nDelegate._currentTranslationObject == null ||
        FlutterI18nDelegate._currentTranslationObject.locale != locale) {
      FlutterI18nDelegate._currentTranslationObject =
          FlutterI18n(translationLoader);
      // HACK afancinelli - send locale to translation object
      //      await FlutterI18nDelegate._currentTranslationObject.load();
      await FlutterI18nDelegate._currentTranslationObject.load(locale: locale);
      // HACK /
    }
    return FlutterI18nDelegate._currentTranslationObject;
  }

• flutter_i18n:

  // HACK afancinelli
  // Future<bool> load() async {
  Future<bool> load({ Locale locale = null }) async {
    // HACK /
    // HACK afancinelli - change locale if not null
    if(locale != null) {
      translationLoader.locale = locale;
    }
    // HACK /
    decodedMap = await translationLoader.load();
    return true;
  }

It works even on IOS simulator.

Regards,
Andrea

**Comment by ilteoood** [comment]
Hi Andrea, thank you so much for your kind words.
I think that I haven't understood your problem, without a proper text format is hard to read the code that you pasted.

BTW, isn't the method refresh useful for your situation?

**Comment by dna-f** [comment]
Hi, my material app is wrapped inside a streambuilder that streams changes to locale.
Every time a change occurs to locale, the whole material app is rebuilt and so its localizationsDelegates. No refresh needed as everything is rebuilt.

I changed the code to propagate the new locale down, when the load method is automatically called.

// await FlutterI18nDelegate._currentTranslationObject.load();
await FlutterI18nDelegate._currentTranslationObject.load(locale: locale);

Do you think that these few changes to the library, can be added to the next version (i don't see any side effect on my app)

• flutter_i18n_delegate:

@override
Future load(final Locale locale) async {
	MessagePrinter.info("New locale: $locale");
	if (FlutterI18nDelegate._currentTranslationObject == null ||
	FlutterI18nDelegate._currentTranslationObject.locale != locale) {
		FlutterI18nDelegate._currentTranslationObject =
		FlutterI18n(translationLoader);
		// HACK
		// await FlutterI18nDelegate._currentTranslationObject.load();
		await FlutterI18nDelegate._currentTranslationObject.load(locale: locale);
		// HACK /
	}
	return FlutterI18nDelegate._currentTranslationObject;
}

• flutter_i18n:

// HACK 
// Future load() async {
Future load({ Locale locale = null }) async {
	if(locale != null) {
		translationLoader.locale = locale;
	}
// HACK /
	decodedMap = await translationLoader.load();
	return true;
}

This is my app:
https://play.google.com/store/apps/details?id=me.newsteam.app
https://apps.apple.com/it/app/newsteam/id1275886767

Changing the language from the menu, you will see the labels changing on the About screen for example

Thanks,
Andrea

**Comment by ilteoood** [comment]
Sorry Andrea, I think you misunderstood my suggestion.
Instead of modify the source code, I suggest you to use the refresh method here documented:
https://github.com/ilteoood/flutter_i18n/blob/master/CHANGELOG.md#030

With this method, you force the library to use only the language that you desire.

**Comment by dna-f** [comment]
Yes I understood :)
But in my case the loading method of the delegate is automatically called by the framework and the problem is simply that the locale parameter of the load method is not passed down to the _currentTranslationObject 
I could change the code to call even the refresh after the material app rebuild but I'd prefer to handle the locale parameter coming with load to change the current translation object field.

But don't worry, it's just an idea.

Have a nice weekend
Andrea

**Comment by ilteoood** [comment]
Why you closed it?

**Comment by dna-f** [comment]
Sorry Matteo, 
it was just a suggestion, not a real issue. That's why I closed it.
But I can reopen it  ;)

Andrea

**Comment by ilteoood** [comment]
I'm trying that on OS X and android emulator, even on an a device with Italian language as first choice the load method return always en_US as locale.
I think that isn't a reliable method.

**Comment by dna-f** [comment]
Thanks Matteo,
that could be. 
In my case i'm driving the default language (italian for example) out the wrapping stream at startup.
That's why I can set Italian, even if the emulator would pass English by default :)
