### ISSUE TITLE
Translate without context

### ISSUE THREAD

**Issue by tomaszgruzla** [ilteoood/flutter_i18n#77]
I would like to translate the text without context e.g. inside a domain service method of my application.
is there any way to do this?
like this example:
final message = FlutterI18n.translate("messgeToTranslate");

**Comment by ilteoood** [comment]
Unfortunately no. 
The context is used by the localization delegate as key to retrieve the instance of FlutterI18n.
The FlutterI18nDelegate register to flutter the FlutterI18n instance that will be used for the translation. That instance is retrieved using the context.

**Comment by nicemanis** [comment]
@ilteoood I had an idea to create a wrapper class around FlutterI18n, where I pass the root context once at the initialization and and store it as a class member that is used throughout the app lifecycle for translations. Would something like that work? Or, would it be possible to create a singleton class for accessing the FlutterI18n instance?

**Comment by nicemanis** [comment]
Otherwise, it's quite inconvenient to get a context inside an API callback or some other asynchronous method just for translations.

**Comment by ilteoood** [comment]
FlutterI18n class is already a singleton facade for the FlutterI18n instance.
The static methods that you use are here for that.
What I can do, is to make public the method _retrieveCurrentInstance(), in order to be able to retrieve the FlutterI18n instance and pass it to your callbacks.

**Comment by nicemanis** [comment]
That sounds good, so the result would be `FlutterI18n.retrieveCurrentInstance().translate("foo.bar")`?

**Comment by ilteoood** [comment]
Nope, the retrieveCurrentInstance always need a build context. You could use the retrieveCurrentInstance to retrieve the instance of FlutterI18n and pass it  as parameter
