### ISSUE TITLE
Feature request: Force locale on app start

### ISSUE THREAD

**Issue by guyzk** [ilteoood/flutter_i18n#8]
Have an option to choose a locale (any - could be different from phones current locale) on app start.
I am not talking about a fallback locale but an app start locale.
Sometimes a users phone can be in English but I want my app to force a different locale.

This is possible with the built in localizations just by adding the "locale" field to the material app but it's not working with this package.

Another nice feature (not sure if possible) is if you could generate a map so that any translation field name would be easily found by the IDE instead of passing a string.
Something like: FlutterI18n.translate(context).hello instead of FlutterI18n.translate(context, 'hello')

**Comment by ilteoood** [comment]
Hi @guyzk,
This is also possible with flutter_18!

Have you tried: https://github.com/ilteoood/flutter_i18n/blob/master/CHANGELOG.md#030?

For the map, is not possible. The IDE don't know the keys that you configured at build time.
