### ISSUE TITLE
Insecure JSON file

### ISSUE THREAD

**Issue by snj07** [ilteoood/flutter_i18n#80]
Firstly congratulations for the awesome library. It's very easy to use and works as expected. I have some concerns about it. The JSON which contains i18n strings is directly accessible and anyone can change it and recompile the app(if the app's signature is not verified). Can we somehow secure it or obfuscate it?

![image](https://user-images.githubusercontent.com/10563759/79344505-90657900-7f4d-11ea-87a2-a08a33c63737.png)

**Comment by defint** [comment]
Hi @snj07 
You can easy override method `loadString` on `FileTranslationLoader` and load your encrypted data from your safe source.

**Comment by defint** [comment]
Here is quick example:

```dart
class SafeTranslationLoader extends FileTranslationLoader {
  Future<String> loadString(final String fileName, final String extension) {
    return __loadFromSafeSource();
  }
}
```

**Comment by ilteoood** [comment]
Hi @snj07,
You can also load your translation file from a remote source, in order to forget about its encryption.

**Comment by snj07** [comment]
Thanks for the quick response guys.
