### ISSUE TITLE
The method of refresh can not use countryCode

### ISSUE THREAD

**Issue by zhbh** [ilteoood/flutter_i18n#82]
This method is that `FlutterI18n.refresh(buildContext, languageCode, {countryCode})`, in which the parameter of countryside that is to be used does not work. I use the version is the 0.13.0.

**Comment by defint** [comment]
Hi @zhbh 
Method `FlutterI18n.refresh` uses `Locale forcedLocale` parameter, which allow you to set locale with or without `countryCode`.
Please see examples inside source code.

**Comment by zhbh** [comment]
> Hi @zhbh
> Method `FlutterI18n.refresh` uses `Locale forcedLocale` parameter, which allow you to set locale with or without `countryCode`.
> Please see examples inside source code.

Thanks, I got it. If I want to use the countryside, it must config `useCountryCode` for the `FlutterI18nDelegate` first. And then the `countryCode`  of the `forcedLocale` can work in the `FlutterI18n.refresh` method.
