### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by zhbh** [ilteoood/flutter_i18n#83]
When I use the below codes:

`
FlutterI18nDelegate(
        translationLoader:
        NamespaceFileTranslationLoader(
          useCountryCode: true,
          namespaces: [ "home" ]
        )
)
`
in the iOS simulator, it happens the Exception `type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'`.

in the pubspec.yaml, some configs likes that 
`
 - assets/flutter_i18n/en/home.json
 - assets/flutter_i18n/zh_CN/home.json
`

there are the same files in the assets folder. The version of the flutter_i18n is the 0.13.0.

I can not figure out why it happens when I use the `NamespaceFileTranslationLoader`?

**Comment by defint** [comment]
Hey
You should use full key to represent string in your JSON file.
For example correct key is `some.correct.key`. But you used `some.correct` key instead.

**Comment by defint** [comment]
@ilteoood 
I think we have to validate this case and throw correct exception to prevent misunderstanding. 
To reproduce it: https://github.com/ilteoood/flutter_i18n/blob/master/example/lib/basic_example.dart#L93
change `button.label.clickMea` to `button.label`.

**Comment by zhbh** [comment]
Thanks a lot. it can solve my issue. And I suggest this situation could be emphasized in the README for new guys.

**Comment by ilteoood** [comment]
@defint 
I agree with you and I'll try to do this on the weekend.
I'll reopen this, as reminder!
