### ISSUE TITLE
Error thrown on YAML load

### ISSUE THREAD

**Issue by killalad** [ilteoood/flutter_i18n#89]
I'm using the YAML format instead of the JSON for the translation files. But the debugger is throwing an error on the line where is the FlutterI18nDelegate loaded (probably because of finding the `en.json` first). When I press `Continue` in the debugger the app loads the YAML files correctly. It is just annoying that I need to skip this error every time.  

`FlutterError (Unable to load asset: assets/i18n/en.json)`

**FluttterI18nDelegate config:**
```
FlutterI18nDelegate(
        translationLoader: FileTranslationLoader(
            useCountryCode: false,
            fallbackFile: 'en',
            basePath: 'assets/i18n',
            forcedLocale:
                WidgetsBinding.instance.window.locale ?? Locale('en')),
)
```

**Comment by ilteoood** [comment]
Hi @killalad ,
Flutter is unable to see what's inside the assets folder, so we have to go for attempts: first we try to load .json, then we try to load .yaml.

Unfortunately, there's no other way to do it.

We can insert a new parameter in order to give more priority to a format than another: what do you think about it? @defint

**Comment by defint** [comment]
Hi @killalad @ilteoood 
We can add two additional classes:

```
class YAMLFileTranslationLoader extends FileTranslationLoader {
  YamlFileTranslationLoader(
      {fallbackFile = "en",
      basePath = "assets/flutter_i18n",
      useCountryCode = false,
      forcedLocale})
      : super(
            fallbackFile: fallbackFile,
            basePath: basePath,
            useCountryCode: useCountryCode,
            forcedLocale: forcedLocale);

  Future<Map> loadFile(final String fileName) async {
    return _decodeFile(fileName, 'yaml', loadYaml);
  }
}
```

and 

```
class JSONFileTranslationLoader extends FileTranslationLoader {
  YamlFileTranslationLoader(
      {fallbackFile = "en",
      basePath = "assets/flutter_i18n",
      useCountryCode = false,
      forcedLocale})
      : super(
            fallbackFile: fallbackFile,
            basePath: basePath,
            useCountryCode: useCountryCode,
            forcedLocale: forcedLocale);

  Future<Map> loadFile(final String fileName) async {
    return _decodeFile(fileName, 'json', json.decode);
  }
}
```

@ilteoood 
Parameter isn't good way, because we should also know about the decode function. I think we need to add this two classes to solve this problem. It also easy to maintenance if we want to add some additional formats.

**Comment by ilteoood** [comment]
Hi @defint, your approch is really good but in this way we are forcing an user to choose only one format.
What if someone want to use both JSON and YAML, as our example app?

My idea was to create a sort of priority queue

**Comment by defint** [comment]
@ilteoood 
We will left `FileTranslationLoader` as it is. This classes will be added separately.

**Comment by killalad** [comment]
Hello @ilteoood @defint,

**Comment by killalad** [comment]
Hello @ilteoood @defint,

Well both the approaches seem to be fine. From my standpoint, I would just use enum parameter with all supported filetypes and the selected (or the default one) would be just prioritized by including first.

**Comment by ilteoood** [comment]
This is now configurable, please upgrade to 0.14.0 :)
